<div class="pheader clearfix"><?php echo isset($aBanner['iAutoID'])?'编辑':'添加'?>轮播图</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iAutoID" type="hidden" value="<?php echo isset($aBanner['iAutoID'])?$aBanner['iAutoID']:''?>">
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 文章ID：</label>
			<div class="col-sm-10">
				<!--<input name="iNewsID" id="iNewsID" validate="!required:请输入文章标题，并选择所匹配文章！" type="hidden" value="" class="form-control input-validate">-->
				<input name="iNewsID" type="text" validate="!digit:请输入文章ID" placeholder="请输入文章ID" value="<?php echo isset($aBanner['sContent'])?$aBanner['sContent']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 图片：</label>
			<div class="col-sm-10">
				<input type="hidden" id="sImage" name="sImage" validate="!required:请上传图片" value="<?php echo isset($aBanner['sImage'])?$aBanner['sImage']:''?>">
				<img id="sImageShow" style="width:120px;height:90px;" src="<?php echo isset($aBanner['sImage'])?Util_Uri::getDFSViewURL($aBanner['sImage']):''?>">
				<input type="button" value="选择" class="plupload" data-target="#sImage" data-img="#sImageShow">
				<span class="text-muted">尺寸大于802*320的清晰图片，文件大小≤2M支持png、jpg</span>
				<span class="validate_checktip"></span>
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label">备注：</label>
			<div class="col-sm-10">
				<input name="sDesc" type="text" placeholder="备注" value="<?php echo isset($aBanner['sDesc'])?$aBanner['sDesc']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<input type="hidden" name="time" id="iTime" value="<?=time()?>">
		<div class="form-group">
			<label class="col-sm-2 control-label">发布时间：</label>
			<div class="col-sm-10">
				<input name="iPublishTime" readonly validate="datetime:true"
					   class="laydatetime form-control input-validate" validate="" type="text"
					   value="<?php echo isset($aBanner['iPublishTime']) ? date('Y-m-d H:i:s',
						   $aBanner['iPublishTime']) : date('Y-m-d H:i:s',
						   time()) ?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>

		<div class="btn-toolbar text-center">
			<input type="hidden" name="iOptype" id="iOptype" value="">
			<?php if (isset($aBanner['iAutoID']) && isset($aBanner['iPublishStatus']) && 1 == $aBanner['iPublishStatus']):?>
				<button id="save" onclick="$(this.form).attr('must', 0); $( '#iOptype' ).val(2)" class="btn btn-primary">下架</button>
			<?php else:?>
				<button id="save" onclick="$(this.form).attr('must', 0); $( '#iOptype' ).val(0)" class="btn btn-primary">保存</button>
			<?php endif;?>
			<button id="preview" onclick="$(this.form).attr('must', 0); $( '#iOptype' ).val('')" class="btn btn-info">预览</button>
			<button id="publish" onclick="$(this.form).attr('must', 1); $( '#iOptype' ).val(1)" class="btn btn-danger">发布</button>
			<button id="cancel" class="btn" onclick="location.href='<?=$sListUrl?>';return false;">取消</button>
		</div>
	</form>
</div>
<script type="text/javascript">
global.sUploadUrl = '<?php echo Yaf_G::getConf('bannerupload', 'url')?>';
global.sDfsViewUrl = '<?php echo Yaf_G::getConf('dfsview', 'url')?>';
</script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/plupload/plupload.full.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/js/upload.js"></script>
<script type="text/javascript">
$(function() {
	$('#sImageShow').click(function(){
		var sImage = $('#sImage').val();
		window.open(getDFSViewURL(sImage, 0, 0, '', 'banner'));
	});

	//提交表单
	$("#myform").validate({submitHandler: function(form) {
		if($('#iOptype').val() == '') {
			form.action = 'http://<?=(Yaf_G::getConf('news', 'domain'));?>/<?=$sCityCode?>/news/index/previewcarousel/';
			form.target = '_blank';
			form.submit();
			return false;
		}
		form.action = '';

	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '<?=$sListUrl?>';
	        }
	    }, 'json');
	    return false;
	}});
});
</script>
<link rel="stylesheet" href="<?php echo $sStaticRoot?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css" />
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>