<div class="pheader clearfix"><?php echo isset($aTag['iTagID']) ? '编辑' : '增加' ?>标签</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iTagID" type="hidden" value="<?php echo isset($aTag['iTagID']) ? $aTag['iTagID'] : '' ?>">

        <div class="form-group">
            <label for="sTagName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 标签：</label>

            <div class="col-sm-10">
                <input name="sTagName" validate="!length:1-6" type="text"
                       value="<?php echo isset($aTag['sTagName']) ? $aTag['sTagName'] : '' ?>" class="form-control input-validate">
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 范围：</label>

            <div class="col-sm-10">
                <div class="col-sm-8" validate="!radio:iCityID:1:城市">
                <label class="radio-inline">
                    <input type="radio" name="iCityID" id="iCityID1" value="0"
                        <?php echo ((isset($aTag['iCityID']) && $aTag['iCityID'] == 0) || !isset($aTag['iTagID'])) ? 'checked' : '' ?>>
                    全国 </label>
                <label class="radio-inline">
                    <input type="radio" name="iCityID" id="iCityID2" value="<?php echo $iCurrCityID; ?>"
                        <?php echo (isset($aTag['iCityID']) && $aTag['iCityID'] > 0) ? 'checked' : '' ?>>
                    当前城市 </label>
                </div>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="sPassword" class="col-sm-2 control-label">标签描述：</label>

            <div class="col-sm-10">
                <textarea name="sDesc" validate="length:5-200"
                          class="form-control input-validate"><?php echo isset($aTag['sDesc']) ? $aTag['sDesc'] : '' ?></textarea>
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="btn-toolbar text-center">
            <button id="save" class="btn btn-primary">保存</button>
            <button id="cancel" class="btn" onclick="location.href='<?=$sListUrl?>';return false;">取消</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = '<?=$sListUrl?>';
                    }
                }, 'json');
                return false;
            }
        });
    });
</script>