<div class="pheader clearfix">标签列表</div>
<div class="pbody clearfix">
    <div class="btn-toolbar list-toolbar">
        <button class="btn btn-primary" id="tag_add">
            <i class="icon-plus"></i> 增加标签
        </button>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="col-sm-1 text-center">#</th>
            <th>标签名称</th>
            <th>区域</th>
            <th>标签描述</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($aList['aList'] as $v) { ?>
            <tr>
                <td class="col-sm-1 text-center"><?php echo $v['iTagID'] ?></td>
                <td><?php echo $v['sTagName'] ?></td>
                <td><?php echo isset($v['sCityName']) ? $v['sCityName'] : '' ?></td>
                <td><?php echo $v['sDesc'] ?></td>
                <td class="text-center">
                    <a href="<?=$sEditUrl?>?id=<?php echo $v['iTagID'] ?>" title="编辑"><i
                            class="icon-pencil icon-large"></i></a>
                    <a class="tag_delete" href="<?=$sDelUrl?>?id=<?php echo $v['iTagID'] ?>" role="button"
                       data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php echo $aList['aPager'] ?>
</div>
<script>
    $('.tag_delete').click(function () {
        if (confirm("您确认要删除该标签吗？")) {
            $.get(this.href, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
        return false;
    });
    $('#tag_add').click(function () {
        location.href = '<?=$sAddUrl?>';
    });
</script>