<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/usercenter.css">
<!--修改密码开始-->
<div class="viewport">
    <header class="UserCenter_head">
        <div class="uc_return">
            <div class="uc_return_l" onclick="window.history.back()">
            </div>
            <div class="uc_return_c">修改密码</div>
        </div>
    </header>
    <section class="logging change_passwd">
        <div class="pl12 tip">请输入<span><?php echo substr_replace($phoneNum, '****', 3, 4); ?></span>收到的验证码</div>
        <ul>
            <li class="bgf p12 outborder mb10">
                <input name="verifyCode" type="text" class="register_pass" placeholder="请输入验证码" id="verifyCode" />
                <span class="verification_code p5 border" id="state_verification"><cite id="but_time"></cite><p>获取验证码</p></span>
            </li>
            <li class="bgf p12 outborder">
                <input name="newPwd" type="password" placeholder="输入新密码"  id="too_new_password"/>
            <s class="warn" id="new_pass_verification" style="display:none;"></s>
            </li>
        </ul>
        <div class="btn_wrap" id="affirm_update">
            <span class="btn">确认修改</span>
        </div>
    </section>
    <section class="tip_dialog" id="tip_dialog"></section>
</div>
<!--修改密码结束-->
<script type="text/javascript">
    $(function () {
        //注册
        $("#affirm_update").on("click", function () {
            //zfx新加
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pamend';
            var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/more';
            var verifyCode = $('#verifyCode').val();
            var newPwd = $('#too_new_password').val();

            if (trim(verifyCode) != "" && trim(newPwd) != "") {

                var param = {verifyCode: verifyCode, newPwd: newPwd};

                $.post(url, param, function (ret) {
                    ret = eval('(' + ret + ')');
                    //  console.log(ret);
                    if (ret.status) {
                        //alert('密码修改成功!');
                        $('#new_pass_verification').hide();
                        $('#tip_dialog').html('密码修改成功').show();
                        setTimeout(function () {
                            $("#tip_dialog").hide(200);
                            location.href = locationUrl;
                        }, 2000)
                        //location.href=locationUrl;
                    } else {
                        //alert(ret.data);
                        if (ret.data == "请填写密码") {
                            $('#new_pass_verification').show();
                        } else if (ret.data == "请填写验证码" || ret.data == "验证码错误或者已经过期") {
                            $('#tip_dialog').html(ret.data).show();
                            setTimeout(function () {
                                $("#tip_dialog").hide(200);
                            }, 2000)
                        }
                    }
                    return false;
                });
            } else {
                if (trim(newPwd) == "") {
                    $('#too_new_password').focus();
                }
                if (trim(verifyCode) == "") {
                    $('#verifyCode').focus();
                }

            }
        });

        //获取验证码
        $("#state_verification").on("click", function () {
            var phone = "<?php echo $phoneNum; ?>";
            var url = "<?php echo $verifycodeUrl; ?>";

            if (trim(phone) != "") {
                setTimeout(function () {
                    $("#state_verification p").html("秒后重新获取");
                }, 1000)
                butTime(31);
                $.get(url + "?mobile=" + phone + "&type=4", function (ret) {
                    ret = eval('(' + ret + ')');
                    //  console.log(ret.data);
                    if (ret.status) {
                        //   console.log(ret.status);
                    }
                    return false;
                });
                //SendSms(phone);
            } else {
                var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pLogin';
                //alert('当前未登陆！请先登陆');
                //location.href=locationUrl;
                $('#tip_dialog').html('当前未登陆！请先登陆').show();
                setTimeout(function () {
                    $("#tip_dialog").hide(200);
                    location.href = locationUrl;
                }, 2000)
            }
        })

    });

    //倒计时
    function butTime(time) {
        var $btn_time = $('#but_time');
        var $state = $('#state_verification');
        $state.unbind("click");

        var t = setInterval(function () {
            time = time - 1;
            // console.log(time);
            if (time == 0) {
                $btn_time.hide();
                $("#state_verification").removeClass('current3');
                $("#state_verification p").html("获取验证码");
                clearInterval(t);
                $state.bind("click", getVerificationCode);
            } else {
                $btn_time.show();
                $btn_time.html(time);
            }
        }, 1000);

    }

    function getVerificationCode() {
        var phone = "<?php echo $phoneNum; ?>";
        var url = "<?php echo $verifycodeUrl; ?>";

        if (phone != "") {
            setTimeout(function () {
                $("#state_verification p").html("秒后重新获取");
            }, 1000)
            butTime(31);
            $.get(url + "?mobile=" + phone + "&type=4", function (ret) {
                ret = eval('(' + ret + ')');
                //  console.log(ret.data);
                if (ret.status) {
                    //  console.log(ret.status);
                }
                return false;
            });
            //SendSms(phone);
        } else {
            var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pLogin';
            //alert('当前未登陆！请先登陆');
            //location.href=locationUrl;
            $('#tip_dialog').html('当前未登陆！请先登陆').show();
            setTimeout(function () {
                $("#tip_dialog").hide(200);
                location.href = locationUrl;
            }, 2000)
        }
    }

    function trim(text) {
        if (typeof (text) == "string")
        {
            return text.replace(/^\s*|\s*$/g, "");
        }
        else
        {
            return text;
        }
    }



</script>
