<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/usercenter.css">
<!--重置密码开始-->
<div class="viewport">
    <header class="UserCenter_head outborder">
        <div class="uc_return">
            <div class="uc_return_l" onclick="window.history.back()">
            </div>
            <div class="uc_return_c">重置密码</div>
        </div>
    </header>
    <section class="logging reset_passwd">
        <ul class="pl12 bgf outborder">
            <li class="p12 border_bottom pl0">
            <s></s>
            <input name="mobile" type="text" placeholder="请输入您的手机号" id="register_phone"/>
            <span class="verification_code p5 border current3" id="state_verification"><cite id="but_time"></cite><p>
                    获取验证码</p></span>
            </li>
            <li class="p12 border_bottom pl0">
            <s class="message_code"></s>
            <input name="verifyCode" type="text" placeholder="请输入短信验证码" id="code_verification"/>
            <s class="warn" id="dx_verification" style="display:none;"></s>
            </li>
            <li class="p12 pl0">
            <s class="set_new_passwd"></s>
            <input name="newPwd" type="password" class="register_pass" placeholder="请设置新密码，6-12位字母或数字"
                   id="register_pass"/>
            <s class="warn" id="pass_verification" style="display:none;"></s>
            </li>
        </ul>
        <div class="btn_wrap" id="register_user">
            <span class="btn">重置密码</span>
        </div>
    </section>
    <section class="tip_dialog" id="tip_dialog"></section>
</div>
<!--重置密码结束-->
<script type="text/javascript">
    $(function () {
        //忘记密码
        $("#register_user").on("click", function () {
            //zfx新加
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pForgetPassword';
            var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pLogin';
            var mobile = $('#register_phone').val();
            var verifyCode = $('#code_verification').val();
            var newPwd = $('#register_pass').val();

            if (trim(mobile) != "" && trim(verifyCode) != "" && trim(newPwd) != "") {
                var param = {mobile: mobile, verifyCode: verifyCode, newPwd: newPwd};

                $.post(url, param, function (ret) {
                    ret = eval('(' + ret + ')');
                    //console.log(ret);
                    if (ret.status) {
                        //alert('密码修改成功！');
                        //location.href=locationUrl;
                        $('#dx_verification').hide();
                        $('#pass_verification').hide();
                        $('#tip_dialog').html('密码修改成功').show();
                        setTimeout(function () {
                            $("#tip_dialog").hide(200);
                            location.href = locationUrl;
                        }, 2000)
                    } else {
                        //alert(ret.data);
                        if (ret.data == "验证码错误或者已经过期" || ret.data == "请填写验证码") {
                            $('#dx_verification').show();
                        } else if (ret.data == "请填写密码") {
                            $('#pass_verification').show();
                        } else if (ret.data == "请填写手机号") {
                            $('#tip_dialog').html('请填写手机号').show();
                            setTimeout(function () {
                                $("#tip_dialog").hide(200);
                            }, 2000)
                        }
                    }
                    return false;
                });
            } else {
                if (trim(newPwd) == "") {
                    $('#register_pass').focus();
                }
                if (trim(verifyCode) == "") {
                    $('#code_verification').focus();
                }
                if (trim(mobile) == "") {
                    $('#register_phone').focus();
                }
            }
        });

        //获取验证码
        $("#state_verification").on("click", function () {
            if ($(this).hasClass("current3")) {
                return
            } else {
                var phone = $("#register_phone").val();
                var url = "<?php echo $verifycodeUrl; ?>";

                if (phone != "") {
                    butTime(31);
                    setTimeout(function () {
                        $("#state_verification p").html("秒后重新获取");
                    }, 1000)
                    $.get(url + "?mobile=" + phone + "&type=2", function (ret) {
                        ret = eval('(' + ret + ')');
                        //console.log(ret.data);
                        if (ret.status) {
                            //console.log(ret.status);
                        }
                        return false;
                    });
                    //SendSms(phone);
                } else {
                    //alert('请填写手机号');
                    $('#tip_dialog').html('请填写手机号!').show();
                    setTimeout(function () {
                        $("#tip_dialog").hide(200);
                    }, 2000)
                }
            }
        })



        //失去焦点时验证手机号是否符合规范
        $("#register_phone").on("blur", checkoutPhone);
        $("#register_phone").on("keyup", checkoutPhone)



    });

    //倒计时
    function butTime(time) {
        var $btn_time = $('#but_time');
        var $state = $('#state_verification');
        $state.unbind("click");

        var t = setInterval(function () {
            time = time - 1;
            //console.log(time);
            if (time == 0) {
                $btn_time.hide();
                $("#state_verification").removeClass('current3');
                $("#state_verification p").html("获取验证码");
                clearInterval(t);
                $state.bind("click", getVerificationCode);
            } else {
                $btn_time.show();
                $btn_time.html(time);
            }
        }, 1000);

    }

    function getVerificationCode() {
        var phone = $("#register_phone").val();
        var url = "<?php echo $verifycodeUrl; ?>";

        if (trim(phone) != "") {
            butTime(31);
            setTimeout(function () {
                $("#state_verification p").html("秒后重新获取");
            }, 1000)
            $.get(url + "?mobile=" + phone + "&type=2", function (ret) {
                ret = eval('(' + ret + ')');
                //console.log(ret.data);
                if (ret.status) {
                    //console.log(ret.status);
                }
                return false;
            });
            //SendSms(phone);
        } else {
            //alert('请填写手机号');
            $('#tip_dialog').html('请填写手机号').show();
            setTimeout(function () {
                $("#tip_dialog").hide(200);
            }, 2000)
        }
    }

    function trim(text) {
        if (typeof (text) == "string")
        {
            return text.replace(/^\s*|\s*$/g, "");
        }
        else
        {
            return text;
        }
    }

    function checkoutPhone() {
        var regExp = /^1[3|4|5|7|8]\d{9}$/;
        var userName = $("#register_phone").val();
        if (regExp.test(userName)) {
            $("#state_verification").removeClass('current3');
        } else {
            $("#state_verification").addClass('current3');
        }
    }
</script>
