<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/usercenter.css">
<!--个人中心开始登录-->
<div class="viewport">
    <header class="UserCenter_head">
        <div class="uc_return">
            <div class="uc_return_l" onclick="window.history.back()"></div>
            <div class="uc_return_c">登录</div>
            <div class="uc_return_r"><a href="<?php echo $sTouchwebRoot ?>/h5/Ucenter/pRegister">注册</a></div>
        </div>
    </header>
    <section class="logging">
        <ul class="bgf pl12 outborder">
            <li class="pt12 pb12 border_bottom">
            <s></s>
            <input name="mobile" type="text" placeholder="请输入您的手机号" id="login_userName" />
            <s class="warn" id="pass1_error" style="display:none;"></s>
            </li>
            <li class="pt12 pb12">
            <s class="uc_logging_password"></s>
            <input name="pwd" type="password" placeholder="请输入您的密码" id="login_Password" />
            <s class="warn" id="pass_error" style="display:none;"></s>
            </li>
        </ul>
        <div class="find_paw"><a href="<?php echo $sTouchwebRoot ?>/h5/Ucenter/pForgetPassword">忘记密码？</a></div>
        <div class="btn_wrap" id="login_user">
            <span class="btn">登 录</span>
        </div>
        <div class="quick_register">
            <div><a href="<?php echo $sTouchwebRoot ?>/h5/Ucenter/pRegister">快速注册></a></div>
        </div>
    </section>
    <section class="tip_dialog" id="tip_dialog"></section>
</div>
<!--个人中心结束登录-->
<script type="text/javascript">
    $(function () {
        $("#login_user").on("click", function () {
            //zfx新加
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pLogin';
            var locationUrl = '<?php echo isset($sLocation) ? $sLocation : $sTouchwebRoot . '/h5/Ucenter/more' ?>';
            var mobile = $("#login_userName").val();
            var pwd = $("#login_Password").val();
            if (trim(mobile) != "" && trim(pwd) != "") {
                var param = {mobile: mobile, pwd: pwd};
                $.post(url, param, function (ret) {
                    ret = eval('(' + ret + ')');
                    //console.log(ret);
                    if (ret.status) {
                        //alert('登陆成功');
                        //location.href=locationUrl;
                        $("#pass1_error").hide();
                        $("#pass_error").hide();
                        $('#tip_dialog').html('登陆成功').show();
                        setTimeout(function () {
                            $("#tip_dialog").hide(200);
                            location.href = locationUrl;
                        }, 2000)
                    } else {
                        //alert(ret.data);
                        if (ret.data == "请填写手机号") {
                            $("#pass1_error").show();
                        } else if (ret.data == "请填写密码") {
                            $("#pass_error").show();
                        } else if (ret.data == "用户名或密码错误") {
                            $('#tip_dialog').html(ret.data).show();
                            setTimeout(function () {
                                $("#tip_dialog").hide(200);
                            }, 2000)
                            //alert(ret.data);
                            $("#pass1_error").hide();
                            $("#pass_error").hide();
                        }
                    }
                    return false;
                })
            } else {
                if (trim(pwd) == "") {
                    $("#pass_error").show();
                    $("#login_Password").focus();
                } else {
                    $("#pass_error").hide();
                }
                if (trim(mobile) == "") {
                    $("#pass1_error").show();
                    $("#login_userName").focus();
                } else {
                    $("#pass1_error").hide();
                }

            }
        });


        //验证手机号是否符合规范
        $("#login_userName").on("keyup", checkPhone);
        $("#login_userName").on("blur", checkPhone);

        $("#login_Password").on("keyup", function () {
            if (trim($(this).val()) != "") {
                $("#pass_error").hide();
            } else {
                $("#pass_error").show();
            }
        });

    });

    function trim(text) {
        if (typeof (text) == "string")
        {
            return text.replace(/^\s*|\s*$/g, "");
        }
        else
        {
            return text;
        }
    }

    function checkPhone() {
        var regExp = /^1[3|4|5|7|8]\d{9}$/;
        var userName = $("#login_userName").val();
        if (regExp.test(userName)) {
            $("#pass1_error").hide();
        } else {
            $("#pass1_error").show();
            $("#login_userName").focus();
        }
    }
</script>
