<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/usercenter.css">
<!--注册开始-->
<div class="viewport">
    <header class="UserCenter_head">
        <div class="uc_return">
            <div class="uc_return_l" onclick="window.history.back()">
            </div>
            <div class="uc_return_c">注册</div>
        </div>
    </header>
    <section class="logging reset_passwd register_page">
        <ul class="bgf pl12 outborder">
            <li class="pt12 pb12 border_bottom">
            <s></s>
            <input type="text" placeholder="请输入您的手机号" id="register_phone" name="mobile"/>
            <span class="verification_code p5 border current3" id="state_verification"><cite id="but_time"></cite><p>
                    获取验证码</p></span>
            </li>
            <li class="pt12 pb12 border_bottom">
            <s class="message_code"></s>
            <input type="text" placeholder="请输入短信验证码" id="code_verification" name="code"/>
            <s class="warn" id="dx_verification" style="display:none;"></s>
            </li>
            <li class="pt12 pb12">
            <s class="set_new_passwd"></s>
            <input name="pwd" type="password" class="register_pass" placeholder="请设置密码，6-12位字母或数字"
                   id="register_pass"/>
            <s class="warn" id="pw_verification" style="display:none;"></s>
            </li>
        </ul>
        <div class="agree">
            <p>注册视为同意<a href="Pagreement">《房价点评网用户协议》</a>，所填信息可用于登录及密码找回，信息将不会公开</p>
        </div>
        <div class="btn_wrap" id="register_user">
            <span class="btn">立即注册</span>
        </div>
        <div class="register_page_b">
            <div>
                <span>已有账号？</span>
                <span><a href="<?php echo $sTouchwebRoot ?>/h5/Ucenter/pLogin">快速登录 ></a></span>
            </div>
        </div>
    </section>
    <section class="tip_dialog" id="tip_dialog"></section>
</div>
<!--注册结束-->
<script type="text/javascript">
    $(function () {
        //注册
        $("#register_user").on("click", function () {
            //zfx新加
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/pRegister';
            var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/more';
            var mobile = $('#register_phone').val();
            var code = $('#code_verification').val();
            var pwd = $('#register_pass').val();


            if (trim(mobile) != "" && trim(code) != "" && trim(pwd) != "") {
                var param = {mobile: mobile, code: code, pwd: pwd};
                $.post(url, param, function (ret) {
                    ret = eval('(' + ret + ')');
                    //  console.log(ret);
                    if (ret.status) {
                        //alert('注册成功');
                        //location.href=locationUrl;
                        $('#dx_verification').hide();
                        $('#pw_verification').hide();
                        $('#tip_dialog').html('注册成功').show();
                        setTimeout(function () {
                            $("#tip_dialog").hide(200);
                            location.href = locationUrl;
                        }, 2000)
                    } else {
                        //alert(ret.data);
                        if (ret.data == "请填写手机号") {
                            $('#tip_dialog').html('请填写手机号').show();
                            setTimeout(function () {
                                $("#tip_dialog").hide(200);
                            }, 2000)
                        } else if (ret.data == "验证码错误或者已经过期" || ret.data == "请填写验证码") {
                            $('#dx_verification').show();
                        } else if (ret.data == "请填写密码") {
                            $('#pw_verification').show();
                        } else if (ret.data == "该手机已经被注册") {
                            $('#tip_dialog').html('该手机已经被注册,请重新填写').show();
                            setTimeout(function () {
                                $("#tip_dialog").hide(200);
                            }, 2000)
                        }

                    }
                    return false;
                });
            } else {
                if (trim(pwd) == "") {
                    $('#register_pass').focus();
                }
                if (trim(code) == "") {
                    $('#code_verification').focus();
                }
                if (trim(mobile) == "") {
                    $('#register_phone').focus();
                }
            }
        });

        //获取验证码
        $("#state_verification").bind("click", function () {
            if ($(this).hasClass("current3")) {
                return
            } else {
                var phone = $("#register_phone").val();
                var url = "<?php echo $verifycodeUrl; ?>";
                if (trim(phone) != "") {
                    butTime(31);
                    setTimeout(function () {
                        $("#state_verification p").html("秒后重新获取");
                    }, 1000)
                    $.get(url + "?mobile=" + phone + "&type=1", function (ret) {
                        ret = eval('(' + ret + ')');
                        //console.log(ret.data);
                        if (ret.status) {
                            // console.log(ret.status);
                        }
                        return false;
                    });
                    //SendSms(phone);
                } else {
                    //alert('请填写手机号');
                    $('#tip_dialog').html('请填写手机号').show();
                    setTimeout(function () {
                        $("#tip_dialog").hide(200);
                    }, 2000)
                }
            }
        });

        //失去焦点时验证手机号是否符合规范
        $("#register_phone").on("blur",checkoutPhone);
        $("#register_phone").on("keyup", checkoutPhone);


    });

    //倒计时
    function butTime(time) {
        var $btn_time = $('#but_time');
        var $state = $('#state_verification');
        $state.unbind("click");

        var t = setInterval(function () {
            time = time - 1;
            //  console.log(time);
            if (time == 0) {
                $btn_time.hide();
                $("#state_verification").removeClass('current3');
                $("#state_verification p").html("获取验证码");
                clearInterval(t);
                $state.bind("click", getVerificationCode);
            } else {
                $btn_time.show();
                $btn_time.html(time);
            }
        }, 1000);
    }

    function getVerificationCode() {
        var phone = $("#register_phone").val();
        var url = "<?php echo $verifycodeUrl; ?>";
        if (trim(phone) != "") {
            butTime(31);
            setTimeout(function () {
                $("#state_verification p").html("秒后重新获取");
            }, 1000)
            $.get(url + "?mobile=" + phone + "&type=1", function (ret) {
                ret = eval('(' + ret + ')');
                //  console.log(ret.data);
                if (ret.status) {
                    //  console.log(ret.status);
                }
                return false;
            });
            //SendSms(phone);
        } else {
            //alert('请填写手机号');
            $('#tip_dialog').html('请填写手机号').show();
            setTimeout(function () {
                $("#tip_dialog").hide(200);
            }, 2000)
        }
    }

    function trim(text) {
        if (typeof (text) == "string")
        {
            return text.replace(/^\s*|\s*$/g, "");
        }
        else
        {
            return text;
        }
    }
    function checkoutPhone() {
        var regExp = /^1[3|4|5|7|8]\d{9}$/;
        var userName = $("#register_phone").val();
        if (regExp.test(userName)) {
            $("#state_verification").removeClass('current3');
        } else {
            $("#state_verification").addClass('current3');
        }
    }
</script>
