<div class="pheader clearfix"><?php echo isset($aCategory['iCategoryID'])?'编辑':'增加'?>分类</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iCategoryID" type="hidden" value="<?php echo isset($aCategory['iCategoryID'])?$aCategory['iCategoryID']:''?>">
		<div class="form-group">
			<label for="sCategoryName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 分类名称：</label>
			<div class="col-sm-10">
				<input name="sCategoryName" validate="!length:2-20" type="text" value="<?php echo isset($aCategory['sCategoryName'])?$aCategory['sCategoryName']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label">分类描述：</label>
			<div class="col-sm-10">
			    <textarea name="sDesc" validate="length:5-255" class="form-control input-validate"><?php echo isset($aCategory['sDesc'])?$aCategory['sDesc']:''?></textarea>
				<span class="validate_checktip"></span>
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='<?=$sListUrl?>';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript">
$(function() {
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '<?=$sListUrl?>';
	        }
	    }, 'json');
		return false;
	}});
});
</script>