<div class="pheader clearfix">来电记录</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <div class="form-group">
            <label for="sTagName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 来电号码：</label>
            <div class="col-sm-10 mt7" id="telphoneormobile">
                <input name="phoneNum"  type="text" maxlength="11" id="phoneNum" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')" class="form-control phonewid fl" placeholder="请填写手机号码" />
                <span class="fl jianju">或</span>
                <input name="Quh"  type="text" maxlength="4" id="Quh"  onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')"  class="form-control quhao fl" placeholder="区号">
                <span class="fl hengg">-</span>
                <input name="Telnum"  type="text" maxlength="8" id="Telnum"  onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')"  class="form-control phonewid fl" placeholder="固话号码">
                 <span class="validate_checktip fl ml15"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="sTagName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 姓名：</label>
            <div class="col-sm-10">
                <input name="name"  id="userName" type="text" class="form-control phonewid fl"   placeholder="请填写用户姓名或称呼" />
                <span class="validate_checktip"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 意向城市：</label>

            <div class="col-sm-10">
                <div  class="radiolist">
                    <?php
                        foreach($citys as $k => $item ) {
                    ?>
                    <label class="radio-inline minw">
                        <input type="radio" name="iCityID" id="iCityID<?php echo $item['id'];?>" value="<?php echo $item['id'];?>">
                        <?php echo $item['name'];?>
                    </label>
                    <?php
                        }
                    ?>
                </div>
                <span class="validate_checktip fl mt5"></span>
            </div>
        </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button id="save" class="btn btn-primary">保存</button>
        </div>
    </div>
    </form>
    <hr>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="col-sm-1 text-center">序号</th>
            <th>分机号</th>
            <th>来电号码</th>
            <th>来电时间</th>
        </tr>
        </thead>
        <tbody>
            <?php if ($hotlineList):?>
                <?php foreach($hotlineList as $key => $aHotLine):?>
                    <tr>
                        <td class="col-sm-1 text-center"><?php echo $key+1;?></td>
                        <td><?php echo $aHotLine['iExt'];?></td>
                        <td><?php echo $aHotLine['sCaller'];?></td>
                        <td><?php echo date('Y-m-d H:i:s', $aHotLine['iCreateTime']);?></td>
                    </tr>
                 <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<style type="text/css">
    .phonewid{width:230px;}.fl{float:left;}.jianju{margin-top:5px;margin-left:15px;}.quhao{width:80px;margin-left:15px;}.hengg{margin:6px;}
    .pbody .minw{min-width: 100px;margin-left:0px;}.radiolist{width:80%;float:left;}.mt5{margin-top:5px;}.ml15{margin-left: 15px;}
</style>
<script type="text/javascript">
    $(function() {
        // 提交整体评价表单
        $("#myform").validate({submitHandler: function(form) {
            flag = 0;
            if(!PhoneandTel()){
                flag = 1;
            }
            if ($.trim($("#userName").val()) == "") {
                $("#userName").siblings(".validate_checktip").addClass("validate_wrong").html("请填写用户姓名或称呼");
                flag = 1;
            } else {
                $("#userName").siblings(".validate_checktip").removeClass("validate_wrong").html('');
            }
            if ($("input[name='iCityID']:checked").length<=0) {
                $(".radiolist").siblings(".validate_checktip").addClass("validate_wrong").html("请选择意向城市");
                flag = 1;
            } else {
                $(".radiolist").siblings(".validate_checktip").removeClass("validate_wrong").html('');
            }
            if ( flag == 1) {
                return false;
            }
            $.post("/Phone/Index/save", $(form).serialize(), function(ret){
                 alert(ret.data);
                 if(ret.status) {
                     location.reload();
                 }
            }, 'json');
            return false;
        }});

    })

    function PhoneandTel(){
        var tflag=1;
        if($("#phoneNum").val()=="" && $("#Quh").val()=="" && $("#Telnum").val()==""){
            $("#telphoneormobile").find(".validate_checktip").addClass("validate_wrong").html("手机或者电话必须填一项！");
            tflag=0;
        }else{
            if($("#phoneNum").val()!=""){
                var phoneNum=$("#phoneNum").val();
                var RegExp=/^1[3|4|5|7|8]\d{9}$/;
                if(!RegExp.test(phoneNum)){
                  $("#telphoneormobile").find(".validate_checktip").addClass("validate_wrong").html("手机号码不正确！");
                    tflag=0;
                }
            }else{
                if($("#Quh").val()=="" || $("#Telnum").val()==""){
                    $("#telphoneormobile").find(".validate_checktip").addClass("validate_wrong").html("区号和电话不能为空！");
                      tflag=0;
                }
            }
        }
        if(tflag){
            $("#telphoneormobile").find(".validate_checktip").removeClass("validate_wrong").html('');
            return true;
        }else{
           return false;
        }
    }

</script>