<link href="<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/bubblePanel/bubblePanel_13b93be4.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/home/home_9d5473c7.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/base/base_2da9a5c3.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    var effectiveCity = ["nanjing", "suzhou", "wuxi", "guangzhou", "shenzhen", "shenyang", "dalian", "fuzhou", "xiamen", "beijing", "shanghai", "zhengzhou", "tianjin", "chongqing", "changchun", "chengdu", "hangzhou", "wuhan", "jinan", "changsha", "xian"];
    var mapCityDic="<?php echo $sStaticRoot ?>/js/web/mapCity/";
</script>
<script src="<?php echo $sStaticRoot ?>/js/web/redirect.js" type="text/javascript"></script>
<script src="<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/lib/base_b0ae69b4.js" type="text/javascript"></script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/lib/tangram/base/base_0118630c.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/lib/tangram/base/base.js'] });</script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/jquery/jquery_ba31c430.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/jquery/jquery.js'] });</script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/jquery_cookie/jquery_cookie_e1872d3b.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/jquery_cookie/jquery_cookie.js'] });</script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/vectorMap/vectorMap_04d33947.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/vectorMap/vectorMap.js'] });</script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/bubblePanel/bubblePanel_25ff3ed1.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/common/ui/bubblePanel/bubblePanel.js'] });</script>
<script type="text/javascript">	F._fileMap({ '<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/home/home_91e6b77c.js': ['<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/home/home.js'] });</script>

<section class="city_wrap clearfix" style="margin:20px auto 0;">
    <div class="row">
        <div class="area_select clearfix">
            <div class="orange_top shadow7 clearfix" id="location_city" style="display: none">
                <span>猜您可能在<em class="city_name"></em></span>
                <cite><a href="javascript:void(0)" class="city_link" title="点击进入">点击进入</a><s></s></cite>
            </div>
            <div class="area_list shadow7 clearfix">
                <cite class="txt_tips">按地理位置选择</cite>
                <div class="area_cons">
                    <dl class="area_citys clearfix">
                        <dt>东北地区</dt>
                        <dd>
                            <a href="/change/shenyang" title="沈阳">沈阳</a>
                            <a href="/change/changchun" title="长春">长春</a>
                            <a href="/change/haerbin" title="哈尔滨">哈尔滨</a>
                        </dd>
                    </dl>
                    <dl class="area_citys clearfix">
                        <dt>华北地区</dt>
                        <dd>
                            <a href="/change/beijing" title="北京">北京</a>
                            <a href="/change/tianjin" title="天津">天津</a>
                            <a href="/change/dalian" title="大连">大连</a>
                            <a href="/change/qingdao" title="青岛">青岛</a>
                            <a href="/change/jinan" title="济南">济南</a>
                        </dd>
                    </dl>
                    <dl class="area_citys clearfix">
                        <dt>华东地区</dt>
                        <dd>
                            <a href="/change/shanghai" title="上海">上海</a>
                            <a href="/change/hangzhou" title="杭州">杭州</a>
                            <a href="/change/nanjing" title="南京">南京</a>
                            <a href="/change/suzhou" title="苏州">苏州</a>
                            <a href="/change/wuxi" title="无锡">无锡</a>
                            <a href="/change/changzhou" title="常州">常州</a>
                            <a href="/change/ningbo" title="宁波">宁波</a>
                            <a href="/change/hefei" title="合肥">合肥</a>
                        </dd>
                    </dl>
                    <dl class="area_citys clearfix">
                        <dt>华南地区</dt>
                        <dd>
                            <a href="/change/shenzhen" title="深圳">深圳</a>
                            <a href="/change/guangzhou" title="广州">广州</a>
                            <a href="/change/xiamen" title="厦门">厦门</a>
                            <a href="/change/changsha" title="长沙">长沙</a>
                            <a href="/change/fuzhou" title="福州">福州</a>
                            <a href="/change/nanning" title="南宁">南宁</a>
                        </dd>
                    </dl>
                    <dl class="area_citys clearfix">
                        <dt>中西部地区</dt>
                        <dd>
                            <a href="/change/wuhan" title="武汉">武汉</a>
                            <a href="/change/chengdu" title="成都">成都</a>
                            <a href="/change/chongqing" title="重庆">重庆</a>
                            <a href="/change/xian" title="西安">西安</a>
                            <a href="/change/zhengzhou" title="郑州">郑州</a>
                            <a href="/change/kunming" title="昆明">昆明</a>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="area_map clearfix">
            <div class="map_bar clearfix">
                <div class="map">
                    <div class="mapContainer">
                        <div id="ieTip" class="ieTip">
                            <a id="ieTipClose" href="javascript:;"><em></em></a>
                            <p>由于您IE浏览器版本较低，无法完整体验城市百科的高大上哦~</p>
                            <p>建议您使用<a target="_blank" href="http://www.baidu.com/s?wd=chrome">chrome浏览器</a>或升级至<a target="_blank" href="http://www.baidu.com/s?wd=IE">IE9</a>或者更高版本，体验更流畅！</p>
                        </div>
                        <div id="mapBox" class="mapBox">
                            <div id="nameLayer" class="extLayer nameLayer"></div>
                            <a id="wholeMapBtn" class="extLayer wholeMapBtn" href="javascript:;"></a>
                            <div id="mapInfoLayer" class="extLayer infoLayer" style="opacity: 1; display: block;"></div>
                            <div id="southChinaSea" class="extLayer southChinaSea" style="left: 1066.5px; top: 477.841px;display: block; opacity: 1;"></div>
                        </div>
                    </div>
                </div>
                <script src="<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/home/onlineCities.js" type="text/javascript"></script>
                <script type="text/javascript">F.use('<?php echo $sStaticRoot ?>/js/web/mapCity/static/usercenter/cityRegion/home/home.js');</script>
            </div>
        </div>
    </div>
</section>
<article class="row clearfix mb20" style="padding-top: 20px;">
    <div class="city_list clearfix">
        <?php foreach ($aCity as $v) { ?>
            <dl class="city_info clearfix">
                <dd>
                    <div class="pic_info"><a href="/change/<?php echo $v["cityDomain"] ?>"><img alt="<?php echo $v["cityName"] ?>" src="<?php echo $v["picUrl"] ?>"></a></div>
                    <div class="txt_info">
                        <p><s class="city_ico"></s><b><?php echo $v["cityName"] ?></b></p>
                        <p>
                            <span><a title="<?php echo $v["cityName"] ?>新房" href="/<?php echo $v["cityDomain"] ?>/xinfang"><?php echo $v["cityName"] ?>新房</a>|</span>
                            <?php if($v["esfEnabled"]){?>
                                <span><a title="<?php echo $v["cityName"] ?>二手房" href="/<?php echo $v["cityDomain"] ?>/esfang"><?php echo $v["cityName"] ?>二手房</a></span>
                            <?php } ?>
                        </p>
                    </div>
                </dd>
            </dl>
        <?php } ?>
        <div class="clearfix"></div>
    </div>
</article>
<script type="text/javascript">
    //城市首页特有css
    $(".headNew_tab").hide();
    $(".city_wap").hide();
    $(".city_list").addClass("city_entrance");
    $(".city_list").css("padding", "0 0 30px 50px");
</script>