<div class="pheader clearfix"><?php echo isset($aRole['iRoleID'])?'编辑':'增加'?>角色</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iRoleID" type="hidden" value="<?php echo isset($aRole['iRoleID'])?$aRole['iRoleID']:''?>">
		<div class="form-group">
			<label for="sRoleName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 角色名称：</label>
			<div class="col-sm-10">
				<input name="sRoleName" validate="!length:2-20" type="text" value="<?php echo isset($aRole['sRoleName'])?$aRole['sRoleName']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sRealName" class="col-sm-2 control-label"><strong style="color:red;">*</strong> 角色描述：</label>
			<div class="col-sm-10">
				<input name="sDesc" type="text" validate="length:2-20"  value="<?php echo isset($aRole['sDesc'])?$aRole['sDesc']:''?>" class="form-control input-validate">
				<span class="validate_checktip"></span>
			</div>
		</div>
		<div class="form-group">
			<label for="sRealName" class="col-sm-2 control-label">权限选择：</label>
			<div class="col-sm-10">
    		    <?php foreach ($aMenuList as $k => $mv) {?>
    		    <?php if ($mv['iLevel'] == 0){
        		        if ($k != 0) {
                            echo "</ul>";
                        }
    		    ?>
    			<ul class="nav" style="float:left;padding:5px;margin-right:20px;-webkit-border-radius:5px;-moz-border-radius:5px;border-radius:5px;border: 1px solid #cccccc;">
    			<?php }?>
    		        <li cid="<?=$mv['iMenuID']?>" pid="<?=$mv['iParentID']?>" id="menu<?=$mv['iMenuID']?>" class="menupp<?=$mv['iParentID']?> <?=$mv['sPath']?> menup<?=$mv['iParentID']?>">
    		            <?php echo str_repeat('&nbsp;', 3*$mv['iLevel'])?>
    		            <i class="icon-minus-sign mopenbtn"></i>
    		            <input name="aModule[]" value="<?=$mv['iMenuID']?>" class="rpcheckbox checkbox-inline" type="checkbox" <?php echo isset($aRole['aModule'])&&in_array($mv['iMenuID'], $aRole['aModule'])?'checked':''?>>
    		            <?php echo $mv['sMenuName']?>
    		        </li>
    		    <?php if (isset($aPermissionList[$mv['iMenuID']])){foreach ($aPermissionList[$mv['iMenuID']] as $pv){?>
    		        <li pid="<?=$pv['iModuleID']?>" class="menupp<?=$pv['iModuleID']?> <?=$mv['sPath']?>  menup<?=$mv['iMenuID']?>">
    		            <?php echo str_repeat('&nbsp;', 3*(2+$mv['iLevel']))?>
    		            <input name="aPermission[]" class="rpcheckbox checkbox-inline" type="checkbox" value="<?=$pv['iPermissionID']?>" <?php echo isset($aRole['aPermission'])&&in_array($pv['iPermissionID'], $aRole['aPermission'])?'checked':''?>>
    		            <?php echo $pv['sPermissionName']?>
    		        </li>
    		    <?php }}?>
    		    <?php }?>
    			</ul>
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/role/list/';return false;">取消</button>
        </div>
	</form>
</div>
<script>
$(function() {
	$('.mopenbtn').click(function(){
		var ptr = $(this).parent();
		if ($(this).hasClass('icon-plus-sign')) {
			$('.menupp' + ptr.attr('cid')).removeClass('hide');
			$(this).removeClass('icon-plus-sign').addClass('icon-minus-sign');
		} else {
			$('.menup' + ptr.attr('cid')).addClass('hide');
		    $(this).removeClass('icon-minus-sign').addClass('icon-plus-sign');
			$('.menupp' + ptr.attr('cid') + ' .mopenbtn').removeClass('icon-minus-sign').addClass('icon-plus-sign');
		}
	});
	$('.rpcheckbox').click(function(){
		var ptr = $(this).parent();
		var checked = this.checked;
		$('.menup' + ptr.attr('cid') + ' > .checkbox-inline').each(function(){
			this.checked = checked;
		});
		if (checked) {
    		while ($('#menu' + ptr.attr('pid')).length > 0) {
    			$('#menu' + ptr.attr('pid') + ' > .checkbox-inline').get(0).checked = true;
    			ptr = $('#menu' + ptr.attr('pid'));
    		}
		}
	});
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            location.href = '/role/list/';
	        }
	    }, 'json');
		return false;
	}});
});
</script>