<div class="pheader clearfix">角色列表</div>
<div class="pbody clearfix">
    <div class="btn-toolbar list-toolbar">
    	<button class="btn btn-primary" id="role_add">
    		<i class="icon-plus"></i> 增加角色
    	</button>
    </div>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="col-sm-1 text-center">#</th>
    			<th>角色名</th>
    			<th>说明</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aList['aList'] as $aRole) {?>
            <tr>
    			<td class="col-sm-1 text-center"><?php echo $aRole['iRoleID']?></td>
    			<td><?php echo $aRole['sRoleName']?></td>
    			<td><?php echo $aRole['sDesc']?></td>
    			<td class="text-center">
    			    <a href="/role/edit?id=<?php echo $aRole['iRoleID']?>" title="编辑"><i class="icon-pencil icon-large"></i></a>
    			    <a class="role_delete" href="/role/del?id=<?php echo $aRole['iRoleID']?>" title="删除"><i class="icon-trash icon-large"></i></a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aList['aPager']?>
</div>
<script>
$('.role_delete').click(function() {
	if (confirm("您确认要删除该角色吗？")) {
		$.get(this.href, function(ret){
			alert(ret.data);
		    if (ret.status) {
			    location.reload();
		    }
		}, 'json');
	}
	return false;
});
$('#role_add').click(function(){
	location.href = '/role/add';
});
</script>