
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
        <title>户型描述</title>
        <script src="<?php echo $sStaticRoot?>/touchweb/lib/requirejs/require.js"  data-main="<?php echo $sStaticRoot?>/touchweb/lib/js/buildinfo.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot?>/touchweb/buildinfo/css/style.css">    
    </head>

    <body>
        <section class="main_section">
            <section class="upshow clearfix">
                <div class="imgshow showborder">
                    <?php echo '<canvas data-src="'.$aHxInfo['Image'].'"></canvas>';?>
                </div>
                <div class="hxcode clearfix">
                    <div class="title fl">A2户型编号</div>
                    <a class="selectfang fl" href="#">在线选房</a>
                </div>

                <div class="oneblock">
                    <div class="l_title">户型：</div>
                    <?php echo '<div class="l_content">'.$aHxInfo['TypeName'].'</div>';?>
                </div>
                <div class="oneblock">
                    <div class="l_title">面积：</div>
                    <?php echo '<div class="l_content">'.$aHxInfo['MinArea'].'㎡-'.$aHxInfo['MinArea'].'㎡</div>';?>
                </div>
                <div class="clearfix"></div>
                <div class="oneblock">
                    <div class="l_title">价格：</div>
                    <?php echo '<div class="l_content">'.$aHxInfo['MinTotalPrice'].'-'.$aHxInfo['MaxTotalPrice'].'万</div>';?>
                </div>
            </section>
            
            <?php
                if(!empty($aHxInfo['Desc'])){
                    echo '<section class="downdesc clearfix">
                        <div class="l_title">户型描述</div>';
                    echo '<p>'.$aHxInfo['Desc'].'</p>';
                    echo '</section>';
                }
            ?>
        </section>
    </body>

    <script>
    var localPath = "<?php echo $sStaticRoot ?>/touchweb/";
    </script>
</html>

