<section class="loginMinbox">
	<div class="clearfix">
		<div class="login_leftmenu">
			<h2>
				<s></s><b>个人设置</b>
			</h2>
			<dl>
				<dt>
					<?php if (!empty($userInfo['HeadImg'])) { ?>
					<img src="<?php echo Model_Util::getFormatImag($userInfo['HeadImg']) ?>"/>
					<?php } else { ?>
					<img src="<?php echo $sStaticRoot?>/web/images/person_img.png" />
					<?php } ?>
				</dt>
				<dd>
					<a href=""><?php echo $userInfo['UserName'] ?></a> <span>普通用户</span>
				</dd>
			</dl>
			<ul>
				<li class="<?php if(isset($userInfo['userinfo'])) {echo $userInfo['userinfo']; }?>">
					<a href="/user/index/userinfo"><s class="s_perinfo"></s>个人资料 </a>
				</li>
				<li class="<?php if(isset($userInfo['editavatar'])) {echo $userInfo['editavatar']; }?>">
					<a href="/user/index/editavatar"><s class="s_editavatar"></s>编辑头像</a>
				</li>
				<?php if(empty($userInfo['Phone'])){ ?>
					<li class="<?php if(isset($userInfo['bangding'])) {echo $userInfo['bangding']; }?>"><a href="/user/index/bindingphone"><s
								class="s_binphone"></s>绑定手机</a></li>
				<?php } ?>
				<li class="<?php if(isset($userInfo['changepassword'])) {echo $userInfo['changepassword']; }?>">
					<a href="/user/index/changepassword"><s class="s_changepassword"></s>修改密码 </a>
				</li>
			</ul>
		</div>
		<div class="login_rightinfo">
			<h2>
				修改密码
			</h2>
			<div class="info_mation_box">
				<dl class="dl_person_info">
					<dt>新密码：</dt>
					<dd>
						<cite>
							<input id="pwd" name="pwd" type="password" value="" />
						</cite><span></span>
					</dd>
				</dl>
				<dl class="dl_person_info" style="padding-bottom: 0;">
					<dt>确认密码：</dt>
					<dd>
						<cite>
							<input id="confirmPwd" name="confirmPwd" type="password" value="" />
						</cite><span></span>
					</dd>
				</dl>
				<dl class="dl_person_info">
					<dt>绑定手机：</dt>
					<dd class="verification_code">
						<em style="line-height: 30px; color: #555;">
							<?php if (empty($userInfo['Phone'])) { ?>
								<a href="/user/index/bindingphone">请先绑定手机</a>
							<?php }else{  echo $userInfo['Phone']; ?>
								<input type="hidden" id="account" value="<?php echo $userInfo['Phone'] ?>"/>
							<?php } ?>
						</em>
					</dd>
				</dl>
				<dl class="dl_person_info">
					<dt>验证码：</dt>
					<dd class="verification_code">
						<cite style="display: inline-block;">
							<input id="VCode" name="VCode" type="text" value="" />
						</cite><a id="getVCode" href="javascript:sendSMS(4)">获取验证码</a> <span style="color: #f07151;">
						</span>
					</dd>
				</dl>
				<dl class="dl_person_info">
					<dt>&nbsp;</dt>
					<dd>
						<div class="loginBtn">
							<input type="button" id="changeSubmit" value="保存" />
						</div>
					</dd>
				</dl>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$(function () {
			$("#pwd").focus(function () {
				$("#pwd").parent().next("span").html("");
				$("#pwd").parent().parent().removeClass("dd_error");
			});
			$("#pwd").blur(function () {
				checkPwd(false, $(this));
			});

			$("#confirmPwd").focus(function () {
				$("#confirmPwd").parent().next("span").html("");
				$("#confirmPwd").parent().parent().removeClass("dd_error");
			});
			$("#confirmPwd").blur(function () {
				checkConfirmPwd(false, $("#pwd"), $(this));
			});

			$("#VCode").focus(function () {
				$("#getVCode").next("span").html("");
				$("#getVCode").parent().removeClass("dd_error");
			});
			$("#VCode").blur(function () {
				//checkVCode(false, $(this), "<?php echo $userInfo['Phone'] ?> ", 4);
			});

			$("#changeSubmit").click(function(){
				var checkPwdResult = checkConfirmPwd(false, $("#pwd"), $("#confirmPwd"));
				var checkCodeResult = checkVCode(false, $("#VCode"), $("#account"), 4);
				if (!(checkPwdResult && checkCodeResult)) {
					return;
				}
				$.post("/user/index/updatePassword", { pwd: $("#pwd").val(),code:$("#VCode").val() }, function (result) {
					if (result.data.msg == 'ok') {
						alert('密码修改成功');
						window.location = "/user/index/userinfo";
					}else{
						alert('密码修改失败');
					}
				},'json');
			})
		});
	</script>
</section>
