<section class="loginMinbox">
	<div class="login_box clearfix">
		<div class="cuccess_box">
			<h2 class="forget_title">
				<s></s>重设密码</h2>
			<form id="formForget">
			<dl class="login_dl">
				<dt><b>手机号码：</b> </dt>
				<dd>
					<cite>
						<input id="account" name="account" type="text" onkeyup="clearNoNumNew(this)" onblur="clearNoNumNew(this)" />
					</cite><span><s></s></span>
				</dd>
			</dl>
			<dl class="login_dl">
				<dt><b>设置密码：</b> </dt>
				<dd>
					<cite>
						<input id="pwd" name="pwd" type="password" />
					</cite><span><s></s></span>
				</dd>
			</dl>
			</form>
			<dl class="login_dl">
				<dt><b>确认密码：</b> </dt>
				<dd>
					<cite>
						<input id="confirmPwd" name="confirmPwd" type="password" />
					</cite><span><s></s></span>
				</dd>
			</dl>
			<dl class="login_dl">
				<dt><b>验证码：</b> </dt>
				<dd class="verification_code">
					<cite>
						<input id="VCode" name="VCode" type="text" />
					</cite><a id="getVCode" href="javascript:sendSMS(2)">获取验证码</a> <span><s></s></span>
				</dd>
			</dl>
			<div class="loginBtn">
				<input type="button" id="changePassword" value="重设密码" />
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
	$(function () {
		var phone = getQueryString("phone");
		if (phone) {
			$("#account").val(phone);
		}
		$("#account").focus(function () {
			$("#account").parent().next("span").html("");
			$("#account").parent().parent().removeClass("dd_error");
		});
		$("#account").blur(function () {
			checkAccount(false, $(this), 1);
		});
		$("#pwd").focus(function () {
			$("#pwd").parent().next("span").html("");
			$("#pwd").parent().parent().removeClass("dd_error");
		});
		$("#pwd").blur(function () {
			checkPwd(false, $(this));
		});

		$("#confirmPwd").focus(function () {
			$("#confirmPwd").parent().next("span").html("");
			$("#confirmPwd").parent().parent().removeClass("dd_error");
		});
		$("#confirmPwd").blur(function () {
			checkConfirmPwd(false, $("#pwd"), $(this));
		});

		$("#VCode").focus(function () {
			$("#getVCode").next("span").html("");
			$("#getVCode").parent().removeClass("dd_error");
		});
		$("#VCode").blur(function () {
			checkVCode(false, $(this), $("#account"), 2);
		});

		$("#changePassword").click(function(){
			var checkPwdResult = checkConfirmPwd(false, $("#pwd"), $("#confirmPwd"));
			var checkCodeResult = checkVCode(false, $("#VCode"), $("#account"), 2);
			if (!(checkPwdResult && checkCodeResult)) {
				return;
			}

			var mobile = $("#account").val();
			var pwd = $("#confirmPwd").val();
			var code = $("#VCode").val();

			$.post("/user/index/forgetpassword", {mobile:mobile,pwd:pwd,code:code}, function (result) {
				if (result.data.msg == 'ok') {
					alert('重设密码成功');
					window.location = "/user/index/login";
				}else{
					alert('重设密码失败');
				}
			},'json');
		})

	});
	/*
	function changePassword() {
		var checkPwdResult = checkConfirmPwd(false, $("#pwd"), $("#confirmPwd"));
		var checkCodeResult = checkVCode(false, $("#VCode"), $("#account"), 4);
		if (!(checkPwdResult && checkCodeResult)) {
			return;
		}

		var mobile = $("#account").val();
		var pwd = $("#confirmPwd").val();
		var code = $("#VCode").val();

		$.post("/user/index/forgetpassword", {mobile:mobile,pwd:pwd,code:code}, function (result) {
			alert(result.errorMessage);
			if (result.code == 1) {
				window.location = "/user/index/login";
			}
		});

	}*/
</script>
