<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=4bfffe2dca93bbf875de0181774419c4"></script>
<script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=3741325988" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="http://qzonestyle.gtimg.cn/qzone/openapi/qc_loader.js" data-appid="101144060" charset="utf-8"></script>
<section class="loginMinbox">
	<div class="login_box clearfix">
		<div class="login_box_left">
			<h2>用户登录</h2>
			<form id="accountLogin">
			<dl class="login_dl">
				<dt><s class="s_phone"></s><b>手机号码：</b> </dt>
				<dd>
					<cite>
						<input id="account" name="account" type="text" onkeyup="clearNoNumNew(this)" onblur="clearNoNumNew(this)"/>
					</cite><span><s></s></span>
				</dd>
			</dl>
			<dl class="login_dl">
				<dt><s class="s_parssword"></s><b>密码：</b> </dt>
				<dd>
					<cite>
						<input id="pwd" name="pwd" type="password" value="" />
					</cite><span><s></s></span>
				</dd>
			</dl>
			</form>
			<p>
				<cite>
					<input type="checkbox" id="rememberMe" name="rememberMe" onchange="checkMe(this.checked)" /><input
						type="hidden" id="remb" value="0" />
					<em><label for="rememberMe">记住我(下次自动登录)</label></em> </cite><a href="/user/index/forgetpassword" id="forget_link">忘记密码？</a>
			</p>
			<div class="loginBtn">
				<input type="button" id="loginSubmit" value="登录">
			</div>
		</div>
		<div class="login_box_right">
			<p>
				<b>还不是房价点评网用户？</b> <a href="/user/index/register">立即注册</a>
			</p>
			<div>
				<span style="color: #555;">更多登录方式： </span>
				<wb:login-button type="3,5" id="wb_connect_btn" onlogin="login" onlogout="logout"
					style="position: relative; top: -2px;">登录按钮</wb:login-button>
				<span id="qqLoginBtn" style="position: relative; top: 7px;"></span>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
    $(function() {
            if (!WB2.checkLogin()) {
            WB2.anyWhere(function (W) {
                W.widget.connectButton({
                    id: "wb_connect_btn",
                    type: "3,5",
                    callback: {
                        login: function (o) {	//登录后的回调函数
                            $.post("/user/index/weblogin", { userName: o.screen_name, sex: o.gender, city: "<?php echo $sCurrCityCode  ?>", Id: o.id },
                                function (data) {
                                    window.location = "https://api.weibo.com/oauth2/authorize?client_id=3741325988&redirect_uri=http://web.ddc.dev.ipo.com/user/index/weiboauthorization/callback&response_type=code";
                                });
                        },
                        logout: function () {	//退出后的回调函数
                        }
                    }
                });
            });
        }
        if (!QC.Login.check()) {
            QC.Login({ btnId: "qqLoginBtn" }, function (oInfo, oOpts) {
                var uname = oInfo.nickname;
                var gender = oInfo.gender;
                var imgu = oInfo.figureurl_1;
                var citycode = "<?php echo $sCurrCityCode  ?>";
                var userid = '<?php echo isset($userInfo['Id']) ? $userInfo['Id']:''  ?>';
                QC.Login.getMe(function (openId, accessToken) {
                    $.post("/user/index/qqlogin", { userName: uname, sex: gender, imgurl: imgu, city: citycode, openId: openId, userID:userid }, function (result) {
                            if(result.data.msg == 'ok' && result.data.sPhone == ''){
                                location.href = "/user/index/snsloginsuccess";
                            }else if(result.data.msg == 'ok' && result.data.sPhone != ''){
                                location.href = "/user/index/userinfo";
                            } else{
                                alert('登陆出错，请稍后尝试');
                            }
                    },'json');
                });
            });
        }
    });

    $("#account").val("<?php echo isset($userInfo['Phone'])?$userInfo['Phone']:'' ?>");
    $("#pwd").val("<?php echo $pwd ?>");
    <?php if(isset($remb)){ ?>
    if (<?php echo $remb ?> == 1) {
        $("#rememberMe").attr("checked","checked");
        $("#remb").val(1);
    }
   <?php } ?>
    loginSubmit(true);
    $("#loginSubmit").click(function () {
        loginSubmit();
    });

    $("#account").focus(function() {
        $("#account").parent().next("span").html("");
        $("#account").parent().parent().removeClass("dd_error");
    });
    $("#account").blur(function() {
        checkAccount(false,$(this),1);
    });
    $("#pwd").focus(function() {
        $("#pwd").parent().next("span").html("");
        $("#pwd").parent().parent().removeClass("dd_error");
    });
    $("#pwd").blur(function() {
        checkPwd(false,$(this));
    });
    /*$("#forget_link").click(function() {
        var account =$.trim($("#account").val());
        if (account.length == 11) {
            $(this).attr("href", "/forget?phone=" + account);
        }
    });*/
    function checkMe(value) {
        if (value) {
            $("#remb").val(1);
        } else {
            $("#remb").val(0);
        }
    }
</script>
