<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/analysis_zs.css">

<body class="bd_bg">
    <!--理想家开始-->
    <div class="viewport">
        <!--头部开始-->
        <header class="tophead lxj">
            <div class="tophead_inner">
                <a href="javascript:history.back()" class="goback"></a>
            </div>
        </header>
        <!--头部开始-->
        <!--户型列表开始-->
        <section class="ljx_con">
            <div class="logo">
                <h1><a href="#"></a></h1>
            </div>
            <div class="slogan">
                <img src="<?php echo $sStaticRoot ?>/touchweb/resource/images/lixiangjia02.png">
            </div>
            <div class="lxj_user">
                <div class="lxj_user_con">
                    <ul>
                        <input type="hidden" id="buildId" value="<?php echo @$aDreamer['id']; ?>" >
                        <li class="lxj_user_name">
                            <input type="text" id="user_name" placeholder="请输入您的姓名"/>
                        </li>
                        <li class="lxj_user_house">
                            <input type="text" id="house_name" placeholder="请输入楼盘名" value="<?php echo @$aDreamer['houseName']; ?>" />
                        </li>
                        <li class="lxj_user_phone">
                            <input type="text" id="user_phone" placeholder="请输入您的手机号码"/>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="lxj_btn">
                <span id="now_btn">立即提交</span><!--点击后加上current类-->
            </div>
        </section>
        <!--户型列表结束-->
    </div>
    <!--理想家结束-->

    <script src="<?php echo $sStaticRoot ?>/touchweb/lib/requirejs/require.js"></script>
    <script>
        require(["<?php echo $sStaticRoot ?>/touchweb/lib/jquery/jquery.min.js"], function () {            
            $('#now_btn').on('click', function () {
                var houseName = $('#house_name').val();
                var userName = $('#user_name').val();
                var userPhone = $('#user_phone').val();
                var buildId = $('#buildId').val();

                $('#now_btn').addClass('current');
                if (houseName != "" && userName != "" && userPhone != "") {
                    var params = {};
                    params.buildId = buildId;
                    params.houseName = houseName;  //此处参数名字要和后台开发匹配, 下同
                    params.userName = userName;
                    params.userPhone = userPhone;

                    postTO(params);
                } else {
                    if(userName == "") {
                        alert("请填写姓名！");
                    }
                    if(userPhone == "") {
                        alert("请填写手机！");
                    }                   
                }
            });
            
            function postTO(params) {
                var regExp = /^1[3|4|5|7|8]\d{9}$/;
                var userPhone = $("#user_phone").val();            //点击立即提交按钮变色,并提交表单
                var request_url = "/ajax/xf/addDreamer"; //此处填写请求地
                if (!regExp.test(userPhone)) {
                    alert('请输入正确的手机号！');
                    return false;
                } 
                try {
                    $.ajax({
                        url: request_url,
                        type: "POST",
                        data: params,
                        timeout: 60000,
                        dataType: "json",
                        async: true,
                        success: function (result) {
                            if (result.status) {
                                alert('提交成功!');
                                history.go(-1);//此处填写请求成功后的跳转地址
                            } else {
                                alert(result.data);
                            }
                        },
                        error: function (result) {
                            alert("请重新填写信息！");
                        }
                    });
                } catch (e) {
                    alert("请求失败，请稍后再试");
                }
            }

        });
    </script>
</body>