<div class="pheader clearfix">作者列表</div>
<div class="pbody clearfix">
    <form class="form-inline search-form" role="form" method="post" id="myform" action="<?=$sListUrl?>">
		<div class="form-group" style="margin-right: 50px;"><a class="btn btn-primary" id="author_add"><i class="icon-plus"></i> 添加作者</a></div>

		<div class="form-group">
			搜索：
			<input type="text" value="<?php echo isset($aParam['sAuthorName'])?$aParam['sAuthorName']:''?>" class="form-control input-sm" name="sAuthorName">
		</div>

        <div class="form-group">
			地区:
            <select class="form-control input-sm" name="iCityID">
                <option value="-1">请选择</option>
                <?php foreach ($__aCityList__ as $k => $v){?>
                <option value="<?php echo $k?>" <?php echo isset($aParam['iCityID'])&&$k==$aParam['iCityID']?'selected':''?>><?php echo $v?></option>
                <?php }?>
            </select>
        </div>
        <div class="form-group">
                                    状态:
            <select class="form-control input-sm" name="iStatus">
                <option value="-1">请选择</option>
                <option value="1" <?php echo isset($aParam['iStatus'])&&1==$aParam['iStatus']?'selected':''?>>有效</option>
                <option value="0" <?php echo isset($aParam['iStatus'])&&0==$aParam['iStatus']?'selected':''?>>无效</option>
            </select>
        </div>
        <input type="submit" id="formbtn" class="btn btn-default btn-sm" value="搜索">
    </form>
    <hr>
    <table class="table table-bordered table-hover">
    	<thead>
    		<tr>
    			<th class="text-center">序号</th>
    			<th class="text-center">作者名</th>
    			<th class="text-center">所属地区</th>
    			<th class="text-center">职位</th>
    			<th class="text-center">状态</th>
    			<th class="text-center">操作</th>
    		</tr>
    	</thead>
    	<tbody>
        <?php foreach ($aAuthorList['aList'] as $v) {?>
            <tr>
    			<td class="text-center"><?=$v['iAuthorID']?></td>
    			<td class="text-center"><?=$v['sAuthorName']?></td>
    			<td class="text-center"><?=$__aCityList__[$v['iCityID']]?></td>
    			<td class="text-center"><?=$v['sPosition']?></td>
    			<td class="text-center"><?php echo $v['iStatus']?'有效':'无效'?></td>
    			<td class="text-center">
					<a href="<?=$sEditUrl?>?iAuthorID=<?php echo $v['iAuthorID']?>" role="button" data-toggle="modal" title="编辑">编辑</a>
    			</td>
    		</tr>
        <?php }?>
    	</tbody>
    </table>
    <?php echo $aAuthorList['aPager']?>
</div>
<script>
$('.author_delete').click(function() {
	if (confirm("您确认要讲该作者置为无效吗？")) {
		$.get(this.href, function(ret){
			//showMsg(ret.data);
			//return false;
			alert(ret.data);
		    if (ret.status) {
			    location.reload();
		    }
		}, 'json');
	}
	return false;
});

$('#author_add').click(function(){
	location.href = '<?=$sAddUrl?>';
});
</script>