<div class="pheader clearfix">审核评论</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="<?=$sCheckUrl?>">
        <input name="iCommentID" type="hidden" value="<?php echo $aComment['iCommentID'] ?>">
        <div class="form-group">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 审核状态：</label>

            <div class="col-sm-10">
                <div class="col-sm-8">
                    <?php foreach ($aCheckStatus as $k => $v) { ?>
                        <label class="radio-inline">
                            <input type="radio" name="iIsCheck" value="<?php echo $k ?>"
                                <?php echo isset($aComment['iIsCheck']) && $k == $aComment['iIsCheck'] ? 'checked' : '' ?>>
                            <?php echo $v ?> </label>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="btn-toolbar text-center">
            <button id="save" class="btn btn-primary">保存</button>
            <button id="cancel" class="btn" onclick="location.href='<?=$sListUrl?>';return false;">取消</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function () {
        $("#myform").validate({
            submitHandler: function (form) {
                $.post(form.action, $(form).serialize(), function (ret) {
                    alert(ret.data);
                    if (ret.status) {
                        location.href = '<?=$sListUrl?>';
                    }
                }, 'json');
                return false;
            }
        });
    });
</script>