<style>
    .tubiao {
        font-weight: bold;
        color: red;
        padding-right: 2px;
    }
    .publish-div {
        margin-bottom: 20px;
    }
</style>
<div class="pheader clearfix">编辑资讯</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iCommentID" id="iCommentID" type="hidden" value="<?php echo isset($aComment['iCommentID']) ? $aComment['iCommentID'] : '' ?>">

        <div class="form-group">
            <label class="col-sm-2 control-label"><span class="tubiao">*</span> 评论内容：</label>

            <div class="col-sm-10">
                <textarea name="sContent" class="form-control input-validate" rows="3"><?php echo isset($aComment['sContent']) ? htmlentities($aComment['sContent']) : '' ?></textarea>
            </div>
        </div>
        <div class="btn-toolbar text-center col-sm-9 publish-div">
            <button id="save" class="btn btn-primary">保存</button>
        </div>
    </form>
</div>
<script type="text/javascript">
        //提交表单
        $(function () {
            $("#myform").validate({
                submitHandler: function (form) {
                    $.post(form.action, $(form).serialize(), function (ret) {
                        alert(ret.data);
                        if (ret.status) {
                            location.href = '<?=$sListUrl?>';
                        }
                    }, 'json');
                    return false;
                }
            });
        });
</script>
