<script src="<?php echo $sStaticRoot ?>/js/web/map/mapold.js"></script>
        <!--[if IE]><script type="text/javascript" src="http://res.fangjia.cric.com/scripts/fe_html5.js"></script><![endif]-->
<!--[if IE 6]>
<script src="http://res0.xzlres.com/web/scripts/ddpng.js" type="text/javascript"></script>
<script type="text/javascript">DD_belatedPNG.fix('.ddpng');</script>
<![endif]-->         

<style type="text/css">
    .amap-container{cursor:url(http://webapi.amap.com/theme/v1.3/openhand.cur),default;}
    .amap-drag{cursor:url(http://webapi.amap.com/theme/v1.3/closedhand.cur),default;}
</style>
<script type="text/javascript">
    localurls = '<?php echo $sStaticRoot ?>';
    window.Searcher.Page = "Map";
    MapConfig.MapData = <?php echo $mapData; ?>;
    MapConfig.InitFilter = {Category: -1, Filter: ""};
    MapConfig.CityName = "<?php echo $cityInfo['CityName'] ?>";
</script>
<input id="keyword" name="keyword" type="hidden" value="">
<input id="cityCode" name="cityCode" type="hidden" value="<?php echo $cityInfo["CityCode"]; ?>">
<section class="map_con">
    <article class="map_left_con">
        <div id="map">
            <div class="map_cell_wrap shadow2" style="display: none; z-index: 1000;">
                <b></b>
                <cite class="b_line"><s class="ico_xf"></s><em>新房(200)</em> </cite>
                <cite><s class="ico_esf"></s><em>二手(200)</em> </cite>
            </div>
        </div>
    </article>
    <article style="position: absolute; right: 0px; top: 0px; width: 502px;">
        <aside id="pannel" class="map_right_con">
            <div class="key_words clearfix">
                您目前在 <?php echo $cityInfo["CityName"]; ?>
                搜索关键字 “ <b>@(data.Keyword)</b> ”</div>
            <div class="no_find_ban clearfix" style="display: none;">
                <s></s><span>找不到任何楼盘？ 尝试<b>放大地图</b>以显示更多结果，或<b>重新选择条件</b>进行搜索！</span>
            </div>
            <div class="result_txt clearfix">
                <span>共找到符合条件的楼盘-个</span>
            </div>
            <div id="units" class="result_list clearfix">
            </div>
        </aside>
        <div class="page" style="position: fixed; bottom: 0; padding: 10px 15px; height: 27px;   background-color: #eee; width: 474px; margin: 0 0 0 -2px;">
        </div>
    </article>
    <div id="FilterCondtion" style="display: none;">
        <div class="filter_cond_box">
        </div>
        <div class="filter_cond_list">
            <cite>
                <em id="TipXf" style="display: inline-block;" onclick="FilterAndApply('XinFang.Enabled');">新房<s>X</s></em>
                <em id="TipXfLevel4" style="display: inline-block;" onclick="FilterAndApply('XinFang.Level4');">新房强烈推荐<s>X</s></em>
                <em id="TipXfLevel3" style="display: inline-block;" onclick="FilterAndApply('XinFang.Level3');">新房推荐<s>X</s></em>
                <em id="TipXfLevel2" style="display: inline-block;" onclick="FilterAndApply('XinFang.Level2');">新房谨慎推荐<s>X</s></em>
                <em id="TipXfLevel1" style="display: inline-block;" onclick="FilterAndApply('XinFang.Level1');">新房不推荐<s>X</s></em>
                <em id="TipEsf" style="display: inline-block;" onclick="FilterAndApply('EsFang.Enabled');">二手房<s>X</s></em>
                <em id="TipEsfLevelA" style="display: inline-block;" onclick="FilterAndApply('EsFang.LevelA');">二手房A级以上<s>X</s></em>
                <em id="TipEsfLevelB" style="display: inline-block;" onclick="FilterAndApply('EsFang.LevelB');">二手房B级-A级<s>X</s></em>
                <em id="TipEsfLevelC" style="display: inline-block;" onclick="FilterAndApply('EsFang.LevelC');">二手房B级以下<s>X</s></em>
                <em id="TipZf" style="display: none;" onclick="FilterAndApply('ZuFang.Enabled');">租房<s>X</s></em>
                <em id="TipZfLevelA" style="display: inline-block;" onclick="FilterAndApply('ZuFang.LevelA');">租房A级以上<s>X</s></em>
                <em id="TipZfLevelB" style="display: inline-block;" onclick="FilterAndApply('ZuFang.LevelB');">租房B级-A级<s>X</s></em>
                <em id="TipZfLevelC" style="display: inline-block;" onclick="FilterAndApply('ZuFang.LevelC');">租房B级以下<s>X</s></em> 
                <em id="TipPriceP5000" style="display: inline-block;" onclick="FilterAndApply('Price.P5000');">均价5千以下<s>X</s></em>
                <em id="TipPriceP10000" style="display: inline-block;" onclick="FilterAndApply('Price.P10000');">均价1万以下<s>X</s></em>
                <em id="TipPriceP15000" style="display: inline-block;" onclick="FilterAndApply('Price.P15000');">均价1-1.5万<s>X</s></em>
                <em id="TipPriceP20000" style="display: inline-block;" onclick="FilterAndApply('Price.P20000');">均价1.5-2万<s>X</s></em>
                <em id="TipPriceP25000" style="display: inline-block;" onclick="FilterAndApply('Price.P25000');">均价2-2.5万<s>X</s></em>
                <em id="TipPriceP30000" style="display: inline-block;" onclick="FilterAndApply('Price.P30000');">均价2.5-3万<s>X</s></em>
                <em id="TipPriceP50000" style="display: inline-block;" onclick="FilterAndApply('Price.P50000');">均价3-5万<s>X</s></em>
                <em id="TipPriceP60000" style="display: inline-block;" onclick="FilterAndApply('Price.P60000');">均价5万以上<s>X</s></em>  
                <em id="TipRentPriceP0000" style="display: inline-block;" onclick="FilterAndApply('RentPrice.P0000');">租金1000以下<s>X</s></em>
                <em id="TipRentPriceP1000" style="display: inline-block;" onclick="FilterAndApply('RentPrice.P1000');">租金1000-2000<s>X</s></em>
                <em id="TipRentPriceP2000" style="display: inline-block;"  onclick="FilterAndApply('RentPrice.P2000');">租金2000-3000<s>X</s></em>
                <em id="TipRentPriceP3000" style="display: inline-block;" onclick="FilterAndApply('RentPrice.P3000');">租金3000-4000<s>X</s></em>
                <em id="TipRentPriceP4000" style="display: inline-block;"  onclick="FilterAndApply('RentPrice.P4000');">租金4000以上<s>X</s></em> 
                <em id="TipAreaA00" style="display: inline-block;" onclick="FilterAndApply('Area.A00');">面积50以下<s>X</s></em>
                <em id="TipAreaA50" style="display: inline-block;" onclick="FilterAndApply('Area.A50');">面积50-80<s>X</s></em>
                <em id="TipAreaA80" style="display: inline-block;" onclick="FilterAndApply('Area.A80');">面积80-110<s>X</s></em>
                <em id="TipAreaA110" style="display: inline-block;" onclick="FilterAndApply('Area.A110');">面积100-130<s>X</s></em>
                <em id="TipAreaA130" style="display: inline-block;" onclick="FilterAndApply('Area.A130');">面积130-150<s>X</s></em> 
                <em id="TipAreaA150" style="display: inline-block;" onclick="FilterAndApply('Area.A150');">面积150-200<s>X</s></em> 
                <em id="TipAreaA200" style="display: inline-block;" onclick="FilterAndApply('Area.A200');">面积200以上<s>X</s></em>
            </cite>
        </div>
    </div>
</section>
<div id="unit_template" style="display: none;">
    <dl class="clearfix" onmouseover="MoveToUnit('$PK')" id="ui$PK">
        <dt>
            <a href="$Url" target="_blank" title="$Tip" onclick="if (MapConfig.MapData.SearchID) {   visitUnit('$Tip', '$Url');   }">
                <img src="$PictureUrl" alt="$Tip" onerror="this.srcX='<?php echo $sStaticRoot ?>/img/news/not_exists.jpg'" />
            </a>
        </dt>
        <dd class="clearfix">
            <h6>
                <s class="$IconClass"></s>
                <a href="$Url" target="_blank" title="$Tip" onclick="if (MapConfig.MapData.SearchID) {   visitUnit('$Tip', '$Url');  }"> $Tip</a>
            </h6>
            <div class="pannel_con clearfix">
                <div class="pannel_left">
                    <div class="txt_info clearfix">
                        <ul class="panel_left">
                            <li><cite>$PriceName2：</cite> <em>$Price2</em> <s>$PriceTag2</s></li>
                            <li><cite>$PriceName：</cite> <em>$Price</em> <s>元/㎡</s></li>
                        </ul>
                    </div>
                </div>
                <div class="pannel_right" evaluationflag="$EvaluationFlag" category="$Category" onmouseover="show_fljy(this)"   onmouseout="$(this).children('cite').show();  $(this).children('span').hide();">
                    <cite><b>综合评定：<em>$TScore</em></b> $Star  </cite>
                    <span class="clearfix" style="display: none;">
                        <a href="$UnitCommentUrl"   target="_blank" class="cor_l">楼盘点评 </a>
                        <a href="$EvaluationUrl" target="_blank" class="cor_g">楼盘测评 </a>
                        <a href="$PriceTableUrl" target="_blank" class="cor_h">价目表 </a>
                        <a href="$DiscountUrl" target="_blank" class="cor_z">优惠折扣 </a>
                    </span>
                </div>
            </div>
            <h5>
                [$Region]$OfficalAddr</h5>
        </dd>
    </dl>
</div>
<div id="unit_template_esf" style="display: none;">
    <dl class="clearfix" onmouseover="MoveToUnit('$PK')" id="ui$PK">
        <dt>
            <a href="$Url" target="_blank" title="$Tip" onclick="if (MapConfig.MapData.SearchID) { visitUnit('$Tip', '$Url');  }">
                <img src="$PictureUrl" alt="$Tip" onerror="this.srcX='<?php echo $sStaticRoot ?>/img/news/not_exists.jpg'" />
            </a>
        </dt>
        <dd>
            <h6>
                <s class="$IconClass"></s>
                <a href="$Url" target="_blank" title="$Tip" onclick="if (MapConfig.MapData.SearchID) {   visitUnit('$Tip', '$Url');  }">  $Tip</a> 
            </h6>
            <div class="pannel_con clearfix">
                <div class="pannel_left">
                    <div class="txt_info clearfix">
                        <ul class="panel_left">
                            <li><cite>$PriceName：</cite> <em>$Price</em> <s>元/㎡</s></li>
                            <li><cite>$PriceName2：</cite> <em>$Price2</em> <s>$PriceTag2</s></li>
                        </ul>
                    </div>
                </div>
                <div class="pannel_right" evaluationflag="$EvaluationFlag" category="$Category" blocktotal="$BlockTotal"  onmouseover="show_fljy_esf(this)" onmouseout="$(this).children('ul').show(); $(this).children('span').hide();">
                    <ul class="panel_right">
                        <li><cite>楼栋数：</cite> <em>$BlockTotal</em> <s>栋</s></li>
                        <li><cite>房间数：</cite> <em>$RoomTotal</em> <s>套</s></li>
                    </ul>
                    <span class="clearfix" style="display: none;">
                        <a href="$Url" target="_blank" class="cor_l"> 小区首页</a> 
                        <a style="display: none" href="$PriceTableUrl" target="_blank" class="cor_g fangjia">  一房一价</a>  
                        <a href="$PriceInfoUrl" target="_blank" class="cor_h">价格行情</a>
                        <a href="$EsfUnitDescriptionUrl" target="_blank" class="cor_z">小区概述</a>
                    </span>
                </div>
            </div>
            <h5>
                [$Region]$OfficalAddr</h5>
        </dd>
    </dl>
</div>
<script type="text/javascript">
    function show_fljy(obj) {
        var flag = $(obj).attr("EvaluationFlag");
        //产品规则：flag==1则显示否则不显示
        //暂行规则：flag==1||flag==-1则显示否则不显示
        if (flag == 1 || flag == -1) {
            $(obj).children('cite').hide();
            $(obj).children('span').show();
        }
    }
    function show_fljy_esf(obj) {
        var flag = $(obj).attr("BlockTotal");
        if (flag > 0) {
            $(obj).children('span').find(".fangjia").show();
            $(obj).children('span').find(".jiusan").hide();
        }
        $(obj).children('ul').hide();
        $(obj).children('span').show();
    };
    $(".city_wap .wap_list").hover(function () {
        $(this).children("ul").show();
    }, function () {
        $(this).children("ul").hide();
    });</script>


<script src="http://webapi.amap.com/maps?v=1.3&key=577a65ddaca22905a96eba25f4a0a94b" type="text/javascript"></script>
<script type="text/javascript">
    $(".city_wap .wap_list").hover(function () {
        $(this).children("ul").show();
    }, function () {
        $(this).children("ul").hide();
    });
    $(function () {
        if ($("#keyword").val() != "") {
            $("#key").val('');
        }
        var windowRes = function () {
            if ($(window).width() <= 1024) {
                $("#pannel").width(325);
                $(".map_left_con").css("margin-right", 325);
                $("#units dl dd").css("width", 175);
                $("#units .pannel_right").css("display", "none");
                $("#map").width($("#Header").width() - ($("#pannel").width() + 2));
            } else {
                $("#pannel").width(502);
                $(".map_left_con").css("margin-right", 502);
                $("#units dl dd").css("width", 355);
                $("#units .pannel_right").css("display", "block");
                $("#map").width($("#Header").width() - ($("#pannel").width() + 2));
            }
        };
        windowRes();
        //自适应高度宽度
        $(window).resize(function () {
            var fixHight = $(window).height() - $("#Header").height();
            $("#pannel").height(fixHight - 60);
            $("#map").height(fixHight);
            $("#map").width($("#Header").width() - ($("#pannel").width() + 2));
            $(".filter_cond_box").width($("#Header").width() - ($("#pannel").width() + 2));
            $(".filter_cond_list").width($("#Header").width() - ($("#pannel").width() + 2) - 60);
            $(".filter_cond_box").height($(".filter_cond_list").height() + 12);
            windowRes();
        }).resize();
    });

</script>
