<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/swiper.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $sStaticRoot ?>/touchweb/resource/css/lixiangjia.css">
<section class="join_now" id="join_now">
    <div class="join_now_alert">
        <div class="alert_name">
            加入理想家俱乐部
            <span class="close" id="close_btn"></span>
        </div>
        <div class="userinfo">
            <ul>
                <li>
                    <span>姓名</span>
                    <input name="name" id="name" type="text"/>
                </li>
                <li>
                    <span>手机</span>
                    <input name="phoneNum" id='phoneNum' type="text" class="phone_number"/>
                    <span id="getverifyCode" class="verification_code current"><cite id="but_time"></cite><p>获取验证码</p></span>
                </li>
                <li>
                    <span>验证码</span>
                    <input name="verifyCode" id="verifyCode" type="text"/>
                </li>
            </ul>
            <div class="join_now_btn" id="join_now_btn">立即加入</div>
        </div>
    </div>
</section>
<!--弹框提示-->
<section class="tip_dialog" id="tip_dialog"></section>
<section class="con">
    <div class="next" id="next_btn"></div>
    <div class="head_wrap">
        <div class="head">
            <div class="uc_return_l return"><a href="index">返回</a></div>
            <div class="pass"><a href="#">跳过</a></div>
        </div>
    </div>
    <!-- Swiper -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <figure class="swiper-slide pic1"></figure>
            <figure class="swiper-slide pic2"></figure>
            <figure class="swiper-slide pic3"></figure>
            <figure class="swiper-slide pic4"></figure>
            <figure class="swiper-slide pic5"></figure>
            <figure class="swiper-slide pic6">
                <div class="join_us" id="join_us_btn">加入我们</div>
            </figure>
            <figure class="swiper-slide pic7">
            	<section class="intro_wrap" id="intro_wrap">
                    <div class="intro_name">
                        <img src="<?php echo $sStaticRoot ?>/touchweb/resource/images/title.png" height="40">
                    </div>
                    <div class="text_wrap">
                        <p>理想家俱乐部由专业购房指导网站房价点评网（fang
                            jiadp.com）发起成立，是一个面向购房人群的会员制俱乐部，目前已覆盖北上广深等30座核心城市。依托房价点评网、克而瑞信息集团的大数据房价专利和400余名房价分析师，为会员构建以“家”为中心的全方位服务体系：找到“理想家”，拿到“理想价”，并由专业分析师提供包括政策解读、选房、购房等一对一私人订制服务。理想家俱乐部，买房不走弯路，一次选好理想之家。</p>
                
                        <div class="intro_btn"><a href="tel:400-810-6999"> 免费咨询 400-810-6999</a></div>
                    </div>
                    <div class="erwei_code">
                        <div class="erwei_code_l">
                            <img src="<?php echo $sStaticRoot ?>/touchweb/resource/images/yewen.png" width="100">
                
                            <p>微信公众号：叶问楼市</p>
                        </div>
                        <div class="erwei_code_r">
                            <img src="<?php echo $sStaticRoot ?>/touchweb/resource/images/shanghai.png" width="100">
                
                            <p>上海买房交流群</p>
                        </div>
                    </div>
                    <p class="website">房价点评网 www.fangjiadp.com</p>
                </section>
            </figure>
        </div>
    </div>
</section>

<script src="<?php echo $sStaticRoot ?>/touchweb/lib/requirejs/require.js"></script>

<script>
    var localPath = '<?php echo $sStaticRoot ?>/touchweb/';
// JavaScript Document
requirejs.config({
    baseUrl: localPath + 'lib',
    //baseUrl: '../lib',
    paths: {
        'jquery': 'jquery/jquery.min',
        'swiper': 'plugs/swiper.min',
    },
    shim: {
        'swiper': {
            deps: ['jquery']
        }
    }
});


require(['jquery', 'swiper'], function () {
var mySwiper  = new Swiper('.swiper-container', {
		slidesPerView : 1,
        paginationClickable: true,
        direction: 'vertical',
		nextButton:"#next_btn",
		onSlideChangeStart: function(swiper){
			//console.log(swiper.activeIndex);
			if(swiper.activeIndex == 6){
				$('.next').hide();
				$('.pass').hide();	
			}else{
				$('.next').show();
				$('.pass').show();
			}
			if(swiper.activeIndex == 5){
				$('.pic7').hide();
			}else{
				$('.pic7').show();
			}
   	 }
    });
	
	//点击跳过显示第五张图片 
	$('.pass').on('click',function(){
		mySwiper .slideTo(5, 500, false);
	})	
	//点击加入我们，出现弹框
	$('#join_us_btn').click(function(e) {
        $('#join_now').show();
    });
	
	//点击叉号关闭弹框
	$('#close_btn').click(function(e) {
        $('#join_now').hide();
    });
	   //获取验证码
        $("#getverifyCode").on("click", function () {
            var phone = $("#phoneNum").val();
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/verifycode';

            if (phone != "") {
				butTime(31);
				setTimeout(function(){$("#state_verification p").html("秒后重新获取");},1000)
                $.get(url + "?mobile=" + phone + "&type=3", function (ret) {
                    ret = eval('(' + ret + ')');
                    console.log(ret.data);
                    if (ret.status) {
                        console.log(ret.status);
                    }
                    return false;
                });
                //SendSms(phone);
            } else {
                //alert('请填写手机号');
				$('#tip_dialog').html('请填写手机号').show();
				setTimeout(function () {
					$("#tip_dialog").hide(200);
                }, 2000)  
            }
        });
        $('#join_now_btn').on('click',function(){
            //zfx新加
            var url = '<?php echo $sTouchwebRoot ?>/h5/index/lixiangjia';
            var locationUrl = '<?php echo $sTouchwebRoot ?>/h5/index/lixiangjia';
            var phoneNum = $('#phoneNum').val();
            var verifyCode = $('#verifyCode').val();
            var name = $('#name').val();
            var param = {phoneNum: phoneNum, verifyCode: verifyCode, name: name};

            $.post(url, param, function (ret) {
                ret = eval('(' + ret + ')');
                console.log(ret);
                if (ret.status) {
                    //alert('加入成功');
                    //location.href=locationUrl;
					$('#tip_dialog').html('加入成功').show();
					setTimeout(function () {
						$("#tip_dialog").hide(200);
						$('#join_now').hide(200);
					}, 2000)
					
                } else {
                    //alert(ret.data);
					if(ret.data=="验证码错误或者已经过期"||ret.data=="参数不全"){
                		$('#tip_dialog').html(ret.data).show();
						setTimeout(function () {
							$("#tip_dialog").hide(200);
						}, 2000)
					}
                }
                return false;
            });
        })
		//失去焦点时验证手机号是否符合规范
		$("#phoneNum").on("blur", function () {

                var regExp = /^1[3|4|5|7|8]\d{9}$/;
                var userName = $("#phoneNum").val();
                if (regExp.test(userName)) {
                    $("#getverifyCode").removeClass('current');
                } else {
                    $("#getverifyCode").addClass('current');
					$("#getverifyCode").unbind('click');
                }                
            })
			
		//倒计时
		function butTime(time){
			var $btn_time = $('#but_time');
			var $state = $('#getverifyCode');
			 $state.unbind("click");
			 
				var t =setInterval(function(){
					time = time - 1;	
					if(time == 0){
						$btn_time.hide();
						$("#getverifyCode").removeClass('current');
						$("#getverifyCode p").html("重新获取验证码");
						clearInterval(t);
						$state.bind("click",getVerificationCode);
					}else{
						$btn_time.show();
						$btn_time.html(time);
					}
					},1000);
           
		}
		
		 function getVerificationCode() {
            var phone = $("#phoneNum").val();
            var url = '<?php echo $sTouchwebRoot ?>/h5/Ucenter/verifycode';

            if (phone != "") {
				butTime(31);
				setTimeout(function(){$("#state_verification p").html("秒后重新获取");},1000)
                $.get(url + "?mobile=" + phone + "&type=3", function (ret) {
                    ret = eval('(' + ret + ')');
                    console.log(ret.data);
                    if (ret.status) {
                        console.log(ret.status);
                    }
                    return false;
                });
                //SendSms(phone);
            } else {
                //alert('请填写手机号');
				$('#tip_dialog').html('请填写手机号').show();
				setTimeout(function () {
					$("#tip_dialog").hide(200);
                }, 2000) 
            }
		 }

		
});
</script>
