<div class="pheader clearfix">模板列表</div>
<div class="pbody clearfix">
    <div class="btn-toolbar list-toolbar list-caozuo">
        <button class="btn btn-primary" id="template_add">
            <i class="icon-plus"></i> 增加模板
        </button>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th class="col-sm-1 text-center">模板ID</th>
            <th>模板名</th>
            <th class="text-center">备注</th>
            <th class="text-center">发布状态</th>
            <th class="text-center">创建时间</th>
            <th class="text-center">最后编辑时间</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($aTemplate['aList'] as $v) { ?>
            <tr id="tr_<?php echo $v['iNewsID'] ?>">
                <td class="col-sm-1 text-center"><?php echo $v['iTempID'] ?></td>
                <td class="col-sm-1 text-center"><?php echo $v['sTitle'] ?></td>
                <td class="col-sm-1 text-center"><?php echo $v['sDesc'] ?></td>
                <td class="col-sm-1 text-center"><?php echo $v['iPublishStatus'] ? '已发布' : '未发布' ?></td>
                <td class="text-center"><?php echo date('Y-m-d H:i', $v['iCreateTime']) ?></td>
                <td class="text-center"><?php echo date('Y-m-d H:i', $v['iUpdateTime']) ?></td>
                <td class="text-center">
                    <a href="<?= $sEditUrl ?>?id=<?php echo $v['iTempID'] ?>" title="编辑"><i
                            class="icon-pencil icon-large"></i></a>
                    <a class="news_delete" href="<?= $sDelUrl ?>?id=<?php echo $v['iTempID'] ?>" role="button"
                       data-toggle="modal" title="删除"><i class="icon-trash icon-large"></i></a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php echo $aTemplate['aPager'] ?>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/laydate/laydate.js"></script>
<script>

    $('.news_delete').click(function () {
        if (confirm("您确认要删除该资讯吗？")) {
            $.get(this.href, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
        return false;
    });
    $('#template_add').click(function () {
        location.href = '<?=$sAddUrl?>';
    });
</script>
<link rel="stylesheet" href="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css"/>
<script type="text/javascript" charset="utf-8"
        src="<?php echo $sStaticRoot ?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot ?>/js/unit.js"></script>
