<section class="bg_f8">
        <article class="minCont clearfix">
            <section id="breadcrumb_nav">
                <nav class="breadcrumb_nav row">
                    <a href="/">房价点评首页</a>
                    <span>&gt;</span>关于我们
                </nav>
            </section>
            <div class="clearfix mb30">
                <aside class="help_tab clearfix">
                    <div class="tab_con clearfix">
                        <ul class="clearfix">
                            <li><a href="/help/index/about" title="关于我们">关于我们<s class="ico_sj"></s></a></li>
                            <li><a href="/help/index/contact" title="联系我们">联系我们<s class="ico_sj"></s></a></li>
                            <li class="bb0"><a href="/help/index/declare" title="网络服务协议">网络服务协议<s class="ico_sj"></s></a></li>
                        </ul>
                    </div>
                </aside>
                <script>
                    $(document).ready(function () {
                        $(".help_tab ul li a").each(function () {
                            if (this.href.toLowerCase() == window.location.toString().toLowerCase()) {
                                $(this).addClass("current");
                            }
                        });
                    });
                </script>
                <div class="help_bar clearfix">
                    <div class="help_con clearfix">
                        <h6>房价点评网——中国第一房产导购平台</h6>
                        <p class="txt_info">房价点评网于2014年6月28日正式上线，是独立的第三方购房指导平台。首创“一房一价+专业测评”服务，包括精确到户的价格指导、楼盘的全面测评报告、分析师专业点评和购买建议，为购房者提供一对一的专家级买房咨询，并定期对楼盘进行评级。目前，房价点评网拥有线上网站、移动客户端、以及线下理想家俱乐部等平台，并获得国家实用新型专利。</p>
                        <p class="txt_info">房价点评网由知名地产机构克而瑞信息集团创立并运营。克而瑞拥有房地产行业最全的大数据、最具口碑的专家团队，在过去12年持续为政府、企业提供全面解决方案的经验基础上，也利用海量数据优势全力为广大购房者提供相关服务。</p>
                        <p class="txt_info">迄今为止，房价点评网已覆盖30座核心城市，连续发布、更新5000余份楼盘测评报告，帮助百万购房者寻找“理想家”、拿到“理想价”，解决老百姓的购房难题，也推动了中国房地产信息公开化和透明化。</p>
                        <h6 class="pt30">房价点评4大优势</h6>
                        <ul class="txt_list clearfix">
                            <li><i>1</i><span>权威专业：由克而瑞信息集团、北京中房研协技术服务有限公司、上海易居房地产研究院牵头研发，联合学术界、产业界相关专家，依托CRIC数据库作为数据基础，历经多年的基础数据准备和理论研究积累，经多方专家论证及严密计算，让用户得到的测评报告与购房指导更加权威专业。</span></li>
                            <li><i>2</i><span>独立第三方：房价点评完全站在第三方的立场，不与购房者、中介、房主产生利益关联，不以楼盘广告或营销为盈利目标，通过建立分析师实名，以及多位分析师参与同一项目测评的机制，确保提供的购房指导意见客观公正，从根本上做到测评结果的客观公正。</span></li>
                            <li><i>3</i><span>全方位测评：凭借克而瑞多年的行业专业测评经验，依靠房价分析师的专业技术，综合楼盘的价格、房源、户型、装修、物业、配套、不利因素等多种因素给出全方位测评报告，定期发布年度、季度、月度、周度楼盘测评榜单，为消费者购房提供专业参考。</span></li>
                            <li><i>4</i><span>定制购房服务：通过网站、移动客户端、微信公众号等线上平台为购房者提供楼盘测评、购房咨询等服务，通过理想家俱乐部、买房金讲堂等线下平台为房价点评网会员提供找到“理想家”、拿到“理想价”等一对一私人订制级服务。</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </article>
</section>
