<div class="pheader clearfix"><?php echo isset($aNews['iNewsID'])?'编辑':'增加'?>资讯</div>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post" action="">
        <input name="iNewsID" type="hidden" value="<?php echo isset($aNews['iNewsID'])?$aNews['iNewsID']:''?>">
		<div class="form-group">
			<label for="sNewsName" class="col-sm-2 control-label">资讯标题：</label>
			<div class="col-sm-10">
				<input name="sTitle" validate="{required:true,minlength:2,maxlength:100}" type="text" value="<?php echo isset($aNews['sTitle'])?$aNews['sTitle']:''?>" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label for="sNewsName" class="col-sm-2 control-label">资讯作者：</label>
			<div class="col-sm-10">
				<input name="sAuthor" validate="{required:true,minlength:2,maxlength:20}" type="text" value="<?php echo isset($aNews['sAuthor'])?$aNews['sAuthor']:''?>" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label for="sNewsName" class="col-sm-2 control-label">资讯分类：</label>
			<div class="col-sm-10">
			    <select name="iCategoryID" class="form-control">
			        <?php foreach ($aCategory as $k => $v){?>
			        <option value="<?php echo $k?>" <?php echo isset($aNews['iCategoryID'])&&$aNews['iCategoryID']==$k?'selected':''?>><?php echo $v?></option>
			        <?php }?>
			    </select>
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label">资讯摘要：</label>
			<div class="col-sm-10">
			    <textarea name="sAbstract" id="sAbstract" validate="{required:true,minlength:10,maxlength:255}"><?php echo isset($aNews['sAbstract'])?$aNews['sAbstract']:''?></textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="sPassword" class="col-sm-2 control-label">资讯内容：</label>
			<div class="col-sm-10">
			    <textarea name="sContent" id="sContent" validate="{required:true,minlength:100,maxlength:65535}"><?php echo isset($aNews['sContent'])?$aNews['sContent']:''?></textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="sNewsName" class="col-sm-2 control-label">资讯来源：</label>
			<div class="col-sm-10">
				<input name="sSource" validate="{url:true}" type="text" value="<?php echo isset($aNews['sSource'])?$aNews['sSource']:''?>" class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label for="sLoupanID" class="col-sm-2 control-label">推送楼盘：</label>
			<div class="col-sm-10">
				<div style="float:left;width:100%">
	                <input type="hidden" name="sLoupanID" id="sLoupanID" value="<?php echo isset($aNews['sLoupanID'])?$aNews['sLoupanID']:''?>">
			        <div class="clear"></div>
			        <div class="selestbeizhu">
			            <span style="float:left;">已选的楼盘：</span>
			            <div id="newsLpSelect" style="">
    			            <?php if(!empty($aLoupan)){foreach ($aLoupan as $k => $v){?>
    			            <a href="javascript:void(0);" class="des_post"><span data-id="<?php echo $k?>"><?php echo $v?></span><i class="icon-remove"></i></a>
    			            <?php }}?>
    			        </div>
			        </div>
			        <div class="selestxuanze" id="newslp">
			            <input type="hidden" id="iLoupanID" value="">
			           	筛选楼盘: <input type="text" id="sLoupanName" style="width:240px;diaplay:inline"> &nbsp;
			           	<input type="button" id="newsLpBtn" value="添  加" class="btn btn-sm">
			        </div>
			    </div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">资讯标签：</label>
			<div class="col-sm-10">
				<div style="float:left;width:100%">
	                <input type="hidden" name="sTag" id="sTag" value="<?php echo isset($aNews['sTag'])?$aNews['sTag']:''?>">
			        <div class="clear"></div>
			        <div class="selestbeizhu">
			            <span style="float:left;">可选3个标签：</span>
			            <div id="newsTagSelect" style="">
    			            <?php if(!empty($aNews['aTag'])){foreach ($aNews['aTag'] as $sTag){?>
    			            <a href="javascript:void(0);" class="des_post"><span><?php echo $sTag?></span><i class="icon-remove"></i></a>
    			            <?php }}?>
    			        </div>
			        </div>
			        <div class="selestxuanze" id="newstags">
			            <?php foreach ($aTag as $sTag){
			            echo '<a href="javascript:void(0);">' . $sTag . '</a>';
			            }?>
						<br>
			           	自定义输入标签: <input type="text" id="newsTagInput" style="width:120px;diaplay:inline"> &nbsp;
			           	<input type="button" id="newsTagBtn" value="添  加" class="btn btn-sm">&nbsp;(最多6个字)
			        </div>
			    </div>
			</div>
		</div>
    	<div class="btn-toolbar text-center">
        	<button id="save" class="btn btn-primary">保存</button>
        	<button id="cancel"class="btn" onclick="location.href='/news/';return false;">取消</button>
        </div>
	</form>
</div>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/ueditor/ueditor.all.js"> </script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript">
var sCityCode = "<?php echo $aCity['sFullPinyin']?>";
$(function() {
	//富文本编辑框
	var opt = {
        //这里可以选择自己需要的工具按钮名称,此处仅选择如下五个
        toolbars:[['undo', 'redo', '|',
                   'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'superscript', 'subscript', 'removeformat', 'formatmatch', 'blockquote', 'pasteplain', '|',
                   'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'selectall', 'cleardoc', '|',
                   'rowspacingtop', 'rowspacingbottom', 'lineheight', '|',
                   'justifyleft', 'justifycenter', 'justifyright', 'justifyjustify', '|',
                   'link', 'unlink', 'horizontal','|', 
                   'customstyle', 'paragraph', 'fontfamily', 'fontsize', '|',
                   'imagenone', 'imageleft', 'imageright', 'imagecenter', '|',
                   'insertimage', 'emotion', 'insertvideo', 'map', 'background']],
        //关闭字数统计
        wordCount:true,
        //关闭elementPath
        elementPathEnabled:true,
        //默认的编辑区域高度
        initialFrameHeight:100,
        //更多其他参数，请参考ueditor.config.js中的配置项
        serverUrl: '/server/ueditor/controller.php'
    };
	var aue = UE.getEditor('sAbstract', opt);
	var cue = UE.getEditor('sContent', opt);

	
	//提交表单
	$("#myform").validate({submitHandler: function(form) {
	    $.post(form.action, $(form).serialize(), function(ret){
	        alert(ret.data);
	        if (ret.status) {
	            //location.href = '/news/';
	        }
	    }, 'json');
	}});

	
	//推送楼盘操作
	$('#newsLpSelect a').click(delNewsLp);
	$('#newsLpBtn').click(function(){
		var newval = $('#sLoupanName').val();
		if (newval.length == 0) {
			alert('请输入楼盘！');
			return false;
		}
		
		var newid = $('#iLoupanID').val();
		if (newid == '') {
			alert('请选择一个楼盘！');
			return false;
		}
		
		var nowval = $('#sLoupanID').val();
		var tmp = nowval.split(',');
		if (tmp.indexOf(newid) != -1) {
			alert('此搂盘已在推存列表中！');
			return false;
		}
		nowval = nowval.length == 0 ? newid : nowval + ',' + newid;
		$('#sLoupanID').val(nowval);
		
		var str = '<a href="javascript:void(0);" class="des_post"><span data-id="'+newid+'">' + newval +'</span><i class="icon-remove"></i></a>';
		$('#newsLpSelect').append(str);
		$('#newsLpSelect a').click(delNewsLp);
		$('#sLoupanName').val('');
		$('#iLoupanID').val('');
		return true;
	});
	function delNewsLp() {
		var str = $(this).find('span').data('id');
		var vals = $('#sLoupanID').val().split(',');
		for (var i = 0; i < vals.length; i++) {
			if (vals[i] == str) {
				vals.splice(i, 1);
				break;
			}
		}
		$('#sLoupanID').val(vals.join(','));
		$(this).remove();
	}

	
	//标签操作
	$('#newstags a').click(function(){
		if ($(this).hasClass('gray')) {
			return false;
		}
		var val = $('#sTag').val();
		if (val.split(',').length == 3) {
			alert('只能添加三个房源标签！');
			return false;
		}
		val = val.length == 0 ? $(this).html() : val + ',' + $(this).html();
		$('#sTag').val(val);
		
		var str = '<a href="javascript:void(0);" class="des_post"><span>' + $(this).html() +'</span><i class="icon-remove"></i></a>';
		$('#newsTagSelect').append($(str));
		$(this).addClass('gray');
		$('#newsTagSelect a').click(delNewsTag);
	});
	$('#newsTagSelect a').click(delNewsTag);
	$('#newsTagBtn').click(function(){
		var newval = $('#newsTagInput').val();
		if (newval.length == 0) {
			alert('请输入标签！');
			return false;
		}
		if(/^[\u4e00-\u9fa5a-zA-Z]+$/.test(newval) == false) { 
			alert("只能输入字母和中文！"); 
			return false; 
		}
		
		var nowval = $('#sTag').val();
		if (nowval.split(',').length == 3) {
			alert('只能添加三个房源标签！');
			return false;
		}
		nowval = nowval.length == 0 ? newval : nowval + ',' + newval;
		$('#sTag').val(nowval);
		
		var str = '<a href="javascript:void(0);" class="des_post"><span>' + newval +'</span><i class="icon-remove"></i></a>';
		$('#newsTagSelect').append($(str));
		$('#newsTagSelect a').click(delNewsTag);
		$('#newsTagInput').val('');
		return true;
	});
	function delNewsTag() {
		var str = $(this).find('span').html();
		var vals = $('#sTag').val().split(',');
		for (var i = 0; i < vals.length; i++) {
			if (vals[i] == str) {
				vals.splice(i, 1);
				break;
			}
		}
		$('#sTag').val(vals.join(','));
		$(this).remove();
		$('#newstags a').each(function(){
			if ($(this).html() == str) {
				$(this).removeClass('gray');
			}
		})
	}
});
</script>
<link rel="stylesheet" href="<?php echo $sStaticRoot?>/jquery-ui/1.11.1/jquery-ui.min.css" type="text/css" />
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/jquery-ui/1.11.1/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $sStaticRoot?>/js/unit.js"></script>